--------------------------------------------------
# **Create Czech text dataset for training**
-------------------------------------------------

In [1]:
!apt install git-lfs

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git-lfs is already the newest version (3.0.2-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

## ***Imports***

In [2]:
import os, sys
import zipfile
import subprocess
import io
import shutil
import json
import polars as pl
import numpy as np
import pyarrow as pa
import pickle

import pyarrow.parquet as pq
import pyarrow.dataset as ds

from huggingface_hub import (
    get_full_repo_name,
    login,
    upload_folder,
    hf_hub_download,
    HfApi
)


from datasets import load_dataset
from kaggle_secrets import UserSecretsClient
from tqdm import tqdm

## ***Hugging Face Login***

In [3]:
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
user_email = user_secrets.get_secret("user_email")
user_name = user_secrets.get_secret("user_name")

login(token=hf_token)

### ***Data files***

1. ***CZLC/cermat_czech_mc***
   
   The **Cermat Czech MultiChoice** dataset was collected from assignments official CERMAT website. The dataset was collected from three tiers of assignments: 6 year, 9 year primary school test and final high school tests (so-called maturita). The assignments were semi-manually extracted from official PDFs available at [CERMAT's website](https://maturita.cermat.cz/menu/testy-a-zadani-z-predchozich-obdobi/matematika/testy-a-zadani-matematika).

    **Collection Date Range:** years 2016-2023

    ***Licensing and Credits***

    The majority of collection work was done by our student co-worker Jan Kapsa. Members of CZLC do not own the test assignments, neither are responsible for their contents.

    **Source:** https://huggingface.co/datasets/CZLC/cermat_czech_mc
 
2. ***hynky/czech-justice-summ-alpaca-long***

    **Source:** https://huggingface.co/datasets/hynky/czech-justice-summ-alpaca-long

3. ***hynky/czech_news_dataset_v2***

    Dataset containing the news articles from major online news outlets collected from 2000-2022.
    Follow-up paper https://arxiv.org/abs/2307.10666 (v1 of the dataset)

    Changes from v1:
        - Better contribution of novinky.cz in later stages
        - More articles, as a mistake in filtering was fixed.

   Collection was done using CmonCrawl.

   The dataset should be used for Research only purposes as I don't have rights for articles itself.

   **Source:** https://huggingface.co/datasets/hynky/czech_news_dataset_v2

4. ***davidadamczyk/czechbench_agree***

   This is an adapted and filtered test subset from the original Czech grammar agreement dataset

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_agree

6. ***davidadamczyk/czechbench_czech_news***

   This is a simplified and subsampled test subset from the original [czech_news_dataset_v2](https://huggingface.co/datasets/hynky/czech_news_dataset_v2).

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_czech_news

8. ***CIIRC-NLP/czech_news_simple-cs***

   **Source:** https://huggingface.co/datasets/CIIRC-NLP/czech_news_simple-cs

   This is a simplified and subsampled test subset from the original czech_news_dataset_v2.

   Only 5 basic news categories are considered:

   - Foreign
   - Local
   - Sports
   - Economy

   The test set includes 200 examples per category, 1000 examples in total. Apart from the category label, each example also contains the article's headline, brief summary, full textual content, optional keywords, original category specification, and URL.

   This dataset was created for use within the [Czech-Bench](https://gitlab.com/jirkoada/czech-bench) evaluation framework.

In [4]:
ds01 = load_dataset("CZLC/cermat_czech_mc")
ds02 = load_dataset("hynky/czech-justice-summ-alpaca-long")
ds03 = load_dataset("hynky/czech_news_dataset_v2")
ds04 = load_dataset("davidadamczyk/czechbench_agree")
ds05 = load_dataset("davidadamczyk/czechbench_czech_news")
ds06 = load_dataset("CIIRC-NLP/czech_news_simple-cs", "default")

README.md: 0.00B [00:00, ?B/s]

test.jsonl: 0.00B [00:00, ?B/s]

Generating test split:   0%|          | 0/649 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/503 [00:00<?, ?B/s]

data/train-00000-of-00001-93f855e5cee8b5(…):   0%|          | 0.00/12.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4560 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00011-c758fbca39d29e(…):   0%|          | 0.00/285M [00:00<?, ?B/s]

data/train-00001-of-00011-04ed5181478f78(…):   0%|          | 0.00/283M [00:00<?, ?B/s]

data/train-00002-of-00011-7bab2e4f395098(…):   0%|          | 0.00/290M [00:00<?, ?B/s]

data/train-00003-of-00011-4f3be47507ad60(…):   0%|          | 0.00/300M [00:00<?, ?B/s]

data/train-00004-of-00011-eba4d38f0a5bd6(…):   0%|          | 0.00/317M [00:00<?, ?B/s]

data/train-00005-of-00011-1532bd3e35e037(…):   0%|          | 0.00/327M [00:00<?, ?B/s]

data/train-00006-of-00011-a90e9830da712d(…):   0%|          | 0.00/337M [00:00<?, ?B/s]

data/train-00007-of-00011-da6a604299b8e7(…):   0%|          | 0.00/328M [00:00<?, ?B/s]

data/train-00008-of-00011-2bd7fa9bb613ff(…):   0%|          | 0.00/312M [00:00<?, ?B/s]

data/train-00009-of-00011-2ccab243ff4f0d(…):   0%|          | 0.00/314M [00:00<?, ?B/s]

data/train-00010-of-00011-271947731579c0(…):   0%|          | 0.00/326M [00:00<?, ?B/s]

data/validation-00000-of-00002-d13428425(…):   0%|          | 0.00/173M [00:00<?, ?B/s]

data/validation-00001-of-00002-b8b386fb0(…):   0%|          | 0.00/175M [00:00<?, ?B/s]

data/test-00000-of-00002-9f5fef591354e92(…):   0%|          | 0.00/178M [00:00<?, ?B/s]

data/test-00001-of-00002-be0d3a48e095e91(…):   0%|          | 0.00/188M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1641471 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/144836 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/144837 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/4.27k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/607 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/92.9k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.64M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/980 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/test-00000-of-00001-8fd5c2a953da2a2(…):   0%|          | 0.00/2.67M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [5]:
print(type(ds01),'\n',ds01)
print(type(ds02),'\n',ds02)
print(type(ds03),'\n',ds03)
print(type(ds04),'\n',ds04)
print(type(ds05),'\n',ds05)
print(type(ds06),'\n',ds06)

<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['type', 'query', 'choices', 'gold', 'context', 'subject', 'difficulty', 'source'],
        num_rows: 649
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['output', 'instruction'],
        num_rows: 4560
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 1641471
    })
    validation: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144836
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144837
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 20
    })
    test: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 607
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 20
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 980
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['url', 'headline', 'brief', 'keywords', 'category', 'content', 'category_unclean'],
        num_rows: 1000
    })
})

### ***We display data files in polars***

In [6]:
df01 = pl.from_arrow(ds01["test"].data.table)
df01.sample(5)

shape: (5, 8)
┌──────┬──────────────┬─────────────┬──────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ type ┆ query        ┆ choices     ┆ gold ┆ context     ┆ subject     ┆ difficulty  ┆ source      │
│ ---  ┆ ---          ┆ ---         ┆ ---  ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str  ┆ str          ┆ list[str]   ┆ i64  ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════╪══════════════╪═════════════╪══════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ MC   ┆ Která z násl ┆ ["A. Jde o  ┆ 2    ┆ <bold>(1)</ ┆ český jazyk ┆ maturitní   ┆ podzim 2021 │
│      ┆ edujících    ┆ prozaický   ┆      ┆ bold>       ┆ a           ┆ zkouška     ┆             │
│      ┆ možností…    ┆ text, rým…  ┆      ┆ Kdyby to    ┆ literatura  ┆             ┆             │
│      ┆              ┆             ┆      ┆ naše…       ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A.        ┆ 2    ┆ Portugalské ┆ český jazyk ┆ šestiletá   ┆ 1. řádný    │
│      ┆ edujících    ┆ Výchozí     ┆      ┆ souostroví  ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ tvrzení …    ┆ text popírá ┆      ┆ Azory, …    ┆ literatura  ┆             ┆             │
│      ┆              ┆ infor…      ┆      ┆             ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. V      ┆ 0    ┆ Do třídy    ┆ český jazyk ┆ čtyřleté    ┆ 3. řádný    │
│      ┆ edujících    ┆ textu se    ┆      ┆ vešel muž s ┆ a           ┆ obory a     ┆ termín 2021 │
│      ┆ tvrzení …    ┆ nevyskytuje ┆      ┆ ostře řez…  ┆ literatura  ┆ nástavbová  ┆             │
│      ┆              ┆ žá…         ┆      ┆             ┆             ┆ st…         ┆             │
│ MC   ┆ Která z násl ┆ ["A.        ┆ 2    ┆ <bold>(1)</ ┆ český jazyk ┆ maturitní   ┆ podzim 2017 │
│      ┆ edujících    ┆ komunikace  ┆      ┆ bold> Malé  ┆ a           ┆ zkouška     ┆             │
│      ┆ možností…    ┆ rodičů s    ┆      ┆ dítě se …   ┆ literatura  ┆             ┆             │
│      ┆              ┆ dětmi…      ┆      ┆             ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. Tento  ┆ 1    ┆ TEXT 1      ┆ český jazyk ┆ čtyřleté    ┆ 1. řádný    │
│      ┆ edujících    ┆ verš není   ┆      ┆ (1)         ┆ a           ┆ obory a     ┆ termín 2022 │
│      ┆ tvrzení …    ┆ osmislabi…  ┆      ┆ Žil jednou  ┆ literatura  ┆ nástavbová  ┆             │
│      ┆              ┆             ┆      ┆ v Čechác…   ┆             ┆ st…         ┆             │
└──────┴──────────────┴─────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
df02 = pl.from_arrow(ds03["train"].data.table)
df02.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Netradičn ┆ Původně   ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2014-10- │
│ ww.novink ┆           ┆ í dřevěná ┆ to byl    ┆   ┆           ┆           ┆           ┆ 14       │
│ y.cz/bydl ┆           ┆ přístavba ┆ obyčejný  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ eni…      ┆           ┆ o…        ┆ cihlov…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Jak na    ┆ Suchá a   ┆ … ┆ []        ┆ 0         ┆ 4         ┆ 2012-07- │
│ ww.novink ┆           ┆ záděry na ┆ odrostlá  ┆   ┆           ┆           ┆           ┆ 12       │
│ y.cz/zena ┆           ┆ rukou     ┆ kůžička u ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /st…      ┆           ┆           ┆ neh…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Věra    ┆ Nová DVD: ┆ Hobit:    ┆ … ┆ [2]       ┆ 2         ┆ 2         ┆ 2014-11- │
│ ww.novink ┆ Míšková"] ┆ Manželská ┆ Šmakova   ┆   ┆           ┆           ┆           ┆ 04       │
│ y.cz/kult ┆           ┆ rána,     ┆ dračí     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ura…      ┆           ┆ Hobi…     ┆ poušť     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ vyc…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Lucie   ┆ Hádka     ┆ Ministr   ┆ … ┆ [2]       ┆ 2         ┆ 1         ┆ 2017-04- │
│ ww.seznam ┆ Stuchlíko ┆ ČSSD v    ┆ nedokázal ┆   ┆           ┆           ┆           ┆ 03       │
│ zpravy.cz ┆ vá"]      ┆ Praze:    ┆ prosadit  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /cl…      ┆           ┆ Ministr   ┆ kan…      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Lu…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://k ┆ ["Daniela ┆ Při       ┆ Velvary - ┆ … ┆ [2]       ┆ 2         ┆ 3         ┆ 2013-06- │
│ ladensky. ┆ Řečínská" ┆ nehodě    ┆ Neobvyklá ┆   ┆           ┆           ┆           ┆ 26       │
│ denik.cz/ ┆ ]         ┆ dodávky a ┆ dopravní  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ neh…      ┆           ┆ vlaku     ┆ n…        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ byl…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df03_train = pl.from_arrow(ds03["train"].data.table)
df03_train.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://p ┆ ["Pavel   ┆ Jako      ┆ České Bud ┆ … ┆ [1]       ┆ 1         ┆ 4         ┆ 2012-07- │
│ rachatick ┆ Kortus"]  ┆ první     ┆ ějovice – ┆   ┆           ┆           ┆           ┆ 26       │
│ y.denik.c ┆           ┆ okusil    ┆ Od středy ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ z/h…      ┆           ┆ led       ┆ u…        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bohumil … ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Petra   ┆ Nemám se  ┆ Drtivou   ┆ … ┆ [2]       ┆ 2         ┆ 5         ┆ 2018-10- │
│ ww.idnes. ┆ Klimková" ┆ za co     ┆ porážku   ┆   ┆           ┆           ┆           ┆ 12       │
│ cz/olomou ┆ ]         ┆ stydět,   ┆ ČSSD v    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ c/z…      ┆           ┆ říká po…  ┆ Olomouc…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Němec     ┆ Do studia ┆ … ┆ []        ┆ 0         ┆ 5         ┆ 2012-10- │
│ ww.novink ┆           ┆ dodělal   ┆ aplikovan ┆   ┆           ┆           ┆           ┆ 19       │
│ y.cz/kokt ┆           ┆ vysokou   ┆ ých věd   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ejl…      ┆           ┆ školu čt… ┆ na …      ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Pavel   ┆ Gorbačov: ┆ Poslední  ┆ … ┆ [1]       ┆ 1         ┆ 5         ┆ 2009-03- │
│ pravy.akt ┆ Vondra"]  ┆ Je na     ┆ vůdce     ┆   ┆           ┆           ┆           ┆ 06       │
│ ualne.cz/ ┆           ┆ čase      ┆ SSSR      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zah…      ┆           ┆ spojit    ┆ kritizuje ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ka…       ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milan   ┆ V noci    ┆ Severní   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2010-07- │
│ ww.irozhl ┆ Kocourek" ┆ pokračova ┆ Irsko     ┆   ┆           ┆           ┆           ┆ 14       │
│ as.cz/zpr ┆ ]         ┆ ly        ┆ zažívá    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ avy…      ┆           ┆ nepokoje  ┆ nejhorší  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ v …       ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df03_validation = pl.from_arrow(ds03["validation"].data.table)
df03_validation.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://z ┆ []        ┆ Kdo byl   ┆ Čína      ┆ … ┆ []        ┆ 0         ┆ 4         ┆ 2020-09- │
│ pravy.akt ┆           ┆ na Tchaj- ┆ zakáže    ┆   ┆           ┆           ┆           ┆ 10       │
│ ualne.cz/ ┆           ┆ wanu,     ┆ vstup na  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zah…      ┆           ┆ nesmí d…  ┆ své       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ území…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Kubalík   ┆ Chicago   ┆ … ┆ []        ┆ 0         ┆ 6         ┆ 2020-08- │
│ ww.irozhl ┆           ┆ znovu     ┆ zdolalo   ┆   ┆           ┆           ┆           ┆ 08       │
│ as.cz/spo ┆           ┆ spasil    ┆ díky      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ rt/…      ┆           ┆ Chicago   ┆ trefě     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ v…        ┆ Dom…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Marek   ┆ Vepřový   ┆ Vepřový   ┆ … ┆ [1]       ┆ 1         ┆ 6         ┆ 2020-05- │
│ ww.idnes. ┆ Burza"]   ┆ tomahawk  ┆ tomahawk  ┆   ┆           ┆           ┆           ┆ 30       │
│ cz/hobby/ ┆           ┆ je        ┆ steak je  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ dom…      ┆           ┆ hvězdou   ┆ zají…     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ le…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://p ┆ ["Jakub   ┆ Dobříš    ┆ Obyvatelé ┆ … ┆ [1]       ┆ 1         ┆ 7         ┆ 2020-12- │
│ ribramsky ┆ Šťástka"] ┆ pro své   ┆ Dobříše   ┆   ┆           ┆           ┆           ┆ 13       │
│ .denik.cz ┆           ┆ občany    ┆ budou     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /zp…      ┆           ┆ pořídí k… ┆ moci z…   ┆   ┆           ┆           ┆           ┆          │
│ https://m ┆ []        ┆ Královnin ┆ Zaměstnan ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2020-06- │
│ agazin.ak ┆           ┆ o letní   ┆ ci zámku  ┆   ┆           ┆           ┆           ┆ 30       │
│ tualne.cz ┆           ┆ sídlo     ┆ Balmoral, ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /ba…      ┆           ┆ trpí kv…  ┆ kt…       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df03_test = pl.from_arrow(ds03["test"].data.table)
df03_test.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://j ┆ ["Jiří    ┆ Muži vyhr ┆ Na        ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2021-09- │
│ ablonecky ┆ Louda"]   ┆ ožovali   ┆ začátku   ┆   ┆           ┆           ┆           ┆ 22       │
│ .denik.cz ┆           ┆ Okamurovi ┆ září se   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /zl…      ┆           ┆ pob…      ┆ na        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ sociální… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Petr    ┆ Konec     ┆ V týmové  ┆ … ┆ [1]       ┆ 1         ┆ 1         ┆ 2021-03- │
│ ww.idnes. ┆ Lundák"]  ┆ sezony?   ┆ teplákovc ┆   ┆           ┆           ┆           ┆ 15       │
│ cz/sport/ ┆           ┆ Mach      ┆ e pozorně ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ vol…      ┆           ┆ vyhlíží   ┆ sl…       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ pře…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Petr    ┆ Rok po    ┆ Následky  ┆ … ┆ [1]       ┆ 1         ┆ 7         ┆ 2022-06- │
│ ww.denik. ┆ Kinšt"]   ┆ ničivé    ┆ bouře,    ┆   ┆           ┆           ┆           ┆ 26       │
│ cz/region ┆           ┆ bouři ve  ┆ která se  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ y/r…      ┆           ┆ Stebně:…  ┆ před …    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Krejčíkov ┆ Tenistka  ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2021-03- │
│ ww.irozhl ┆           ┆ á si      ┆ Barbora   ┆   ┆           ┆           ┆           ┆ 15       │
│ as.cz/spo ┆           ┆ vylepšila ┆ Krejčíkov ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ rt/…      ┆           ┆ žebříč…   ┆ á se…     ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ []        ┆ "To je    ┆ "Chuck    ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2021-05- │
│ pravy.akt ┆           ┆ Chuck     ┆ Norris,   ┆   ┆           ┆           ┆           ┆ 03       │
│ ualne.cz/ ┆           ┆ Norris?"  ┆ James     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zah…      ┆           ┆ Video z … ┆ Bond,     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Joh…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df04_train = pl.from_arrow(ds04["train"].data.table)
df04_train.sample(5)

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ ____ se na postupu a oficiální… ┆ ["Domluvila", "Domluvilo", … "… ┆ 2          │
│ Pondělí ____ očekávání meteoro… ┆ ["splnila", "splnilo", … "spln… ┆ 1          │
│ Pestrý program složený z taneč… ┆ ["byla", "bylo", … "byl"]       ┆ 4          │
│ Je to kruté ale ____ jsem takt… ┆ ["využila", "využilo", … "využ… ┆ 4          │
│ Ten, kdo mě zná, by asi ____ k… ┆ ["mohla", "mohlo", … "mohl"]    ┆ 4          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [12]:
df04_test = pl.from_arrow(ds04["test"].data.table)
df04_test.sample(5)

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ Kamarádce zase v Iscare o žehl… ┆ ["měla", "mělo", … "měl"]       ┆ 0          │
│ Přijímání projektů se ____ dos… ┆ ["uskutečnila", "uskutečnilo",… ┆ 1          │
│ Spolu jsme také ____ dohromady… ┆ ["dala", "dalo", … "dal"]       ┆ 2          │
│ Své přátele ____ do pasti a ne… ┆ ["zatáhla", "zatáhlo", … "zatá… ┆ 4          │
│ ____ se ho 22 dětí z Krouny, P… ┆ ["Účastnila", "Účastnilo", … "… ┆ 1          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [13]:
df05_train = pl.from_arrow(ds05["train"].data.table)
df05_train.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Vojáci    ┆ Bulharský ┆ … ┆ 4         ┆ 2021-06-0 ┆ 1         ┆ 11       │
│ ww.irozhl ┆           ┆ USA při   ┆ majitel   ┆   ┆           ┆ 3         ┆           ┆          │
│ as.cz/zpr ┆           ┆ cvičení v ┆ továrničk ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ avy…      ┆           ┆ Bulha…    ┆ y n…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Martin  ┆ Vizita:   ┆ Britský   ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2         ┆ 131      │
│ ww.seznam ┆ Čaban"]   ┆ Jak pošťo ┆ vědecký   ┆   ┆           ┆ 8         ┆           ┆          │
│ zpravy.cz ┆           ┆ uchnout k ┆ časopis   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ očk…      ┆ Nature…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Nejbohatš ┆ Šéf       ┆ … ┆ 3         ┆ 2021-04-0 ┆ 7         ┆ 32       │
│ ww.idnes. ┆           ┆ í člověk  ┆ americké  ┆   ┆           ┆ 7         ┆           ┆          │
│ cz/ekonom ┆           ┆ na světě  ┆ interneto ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ je …      ┆ vé spole… ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Kateřin ┆ Hypotéka  ┆ Hypotéka  ┆ … ┆ 5         ┆ 2021-10-2 ┆ 7         ┆ 19       │
│ pravy.akt ┆ a Hovorko ┆ jako      ┆ na 40 i   ┆   ┆           ┆ 9         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ dědictví. ┆ více let  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ eko…      ┆           ┆ Banky …   ┆ se m…     ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Kateřin ┆ Banky v   ┆ Po        ┆ … ┆ 4         ┆ 2021-04-2 ┆ 7         ┆ 141      │
│ pravy.akt ┆ a Hovorko ┆ Česku     ┆ několika  ┆   ┆           ┆ 9         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ prochází  ┆ letech,   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ eko…      ┆           ┆ revoluc…  ┆ kdy se o  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ k…        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df05_test = pl.from_arrow(ds05["test"].data.table)
df05_test.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://m ┆ ["Boris   ┆ Don Juan  ┆ Plameny   ┆ … ┆ 1         ┆ 2022-06-1 ┆ 4         ┆ 132      │
│ agazin.ak ┆ Klepal"]  ┆ jako fant ┆ žhnoucí   ┆   ┆           ┆ 3         ┆           ┆          │
│ tualne.cz ┆           ┆ asmagorie ┆ touhy,    ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /ku…      ┆           ┆ kr…       ┆ nedosti…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Josef   ┆ Co        ┆ Jedenáct  ┆ … ┆ 5         ┆ 2021-07-1 ┆ 4         ┆ 179      │
│ ww.irozhl ┆ Kaňka"]   ┆ vznikne,  ┆ Cen       ┆   ┆           ┆ 6         ┆           ┆          │
│ as.cz/kul ┆           ┆ když      ┆ Grammy,   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ tur…      ┆           ┆ spojíte   ┆ deset     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Foo F…    ┆ stu…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Filip   ┆ Slovenský ┆ Během     ┆ … ┆ 5         ┆ 2021-10-1 ┆ 1         ┆ 112      │
│ ww.seznam ┆ Harzer"]  ┆ guvernér  ┆ dvou      ┆   ┆           ┆ 5         ┆           ┆          │
│ zpravy.cz ┆           ┆ uvázl v   ┆ týdnů je  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ sít…      ┆ to už     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ třet…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Veronik ┆ Drama     ┆ Na        ┆ … ┆ 6         ┆ 2021-03-2 ┆ 4         ┆ 105      │
│ ww.novink ┆ a Rodrigu ┆ Bílá      ┆ vlastní   ┆   ┆           ┆ 7         ┆           ┆          │
│ y.cz/kult ┆ ez"]      ┆ nemoc v   ┆ kůži      ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ura…      ┆           ┆ době      ┆ zažil     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ covidu…   ┆ hrůzy vá… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Daniela ┆ „Cesta    ┆ Mezi nejč ┆ … ┆ 3         ┆ 2022-03-2 ┆ 2         ┆ 10       │
│ ww.seznam ┆ Přádová"] ┆ byla moc  ┆ astější   ┆   ┆           ┆ 3         ┆           ┆          │
│ zpravy.cz ┆           ┆ těžká.“   ┆ pacienty  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ Ukraji…   ┆ nově…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df06 = pl.from_arrow(ds06["test"].data.table)
df06.sample(5)

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────┬─────────────┬─────────────┐
│ url          ┆ headline     ┆ brief        ┆ keywords     ┆ category ┆ content     ┆ category_un │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---      ┆ ---         ┆ clean       │
│ str          ┆ str          ┆ str          ┆ list[str]    ┆ i64      ┆ str         ┆ ---         │
│              ┆              ┆              ┆              ┆          ┆             ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════╪═════════════╪═════════════╡
│ https://www. ┆ Ekonom o     ┆ Největší     ┆ ["Avast",    ┆ 5        ┆ Ondřej      ┆ Ekonomika   │
│ irozhlas.cz/ ┆ fúzi Avastu: ┆ obchod v     ┆ "Avast       ┆          ┆ Vlček fúzi  ┆             │
│ ekonom…      ┆ Pro Česk…    ┆ českém       ┆ software", … ┆          ┆ zdůvodnil   ┆             │
│              ┆              ┆ byzny…       ┆ …            ┆          ┆ na…         ┆             │
│ https://www. ┆ Ve           ┆ Ve           ┆ ["Valašské   ┆ 2        ┆ „Do         ┆ Regiony     │
│ seznamzpravy ┆ Valašských   ┆ Valašských   ┆ klobouky",   ┆          ┆ Osvětimi a  ┆             │
│ .cz/cl…      ┆ Kloboukách   ┆ Kloboukách   ┆ "Holokau…    ┆          ┆ Terezína    ┆             │
│              ┆ bude …       ┆ na Zl…       ┆              ┆          ┆ byli d…     ┆             │
│ https://www. ┆ V            ┆ Současná     ┆ ["Česká      ┆ 2        ┆ Navíc bude  ┆ Regiony     │
│ seznamzpravy ┆ Ostopovicích ┆ knihovna     ┆ republika",  ┆          ┆ nový sál    ┆             │
│ .cz/cl…      ┆ postaví      ┆ dosluhuje a  ┆ "Jihomorav…  ┆          ┆ sloužit za… ┆             │
│              ┆ novou k…     ┆ …            ┆              ┆          ┆             ┆             │
│ https://www. ┆ Po           ┆ V Libanonu   ┆ ["Libanon",  ┆ 1        ┆ Energetická ┆ Zprávy ze   │
│ irozhlas.cz/ ┆ 24hodinovém  ┆ se podařilo  ┆ "Palivo", …  ┆          ┆ síť v zemi  ┆ světa       │
│ zpravy…      ┆ výpadku v    ┆ obnovit…     ┆ "Blízk…      ┆          ┆ přestal…    ┆             │
│              ┆ Liban…       ┆              ┆              ┆          ┆             ┆             │
│ https://www. ┆ Konec        ┆ Nová         ┆ ["Ústecký    ┆ 2        ┆ „Nová hala  ┆ Kraje       │
│ idnes.cz/ust ┆ nočnímu      ┆ sportovní    ┆ kraj", "Petr ┆          ┆ by měla     ┆             │
│ i/zpra…      ┆ trénování či ┆ hala zřejmě  ┆ globočn…     ┆          ┆ sloužit     ┆             │
│              ┆ děl…         ┆ vyr…         ┆              ┆          ┆ pri…        ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────┴─────────────┴─────────────┘

### ***Creating a summary data file***

In [16]:
def build_unified_contexts(ds01, ds02, ds03, ds04, ds05, ds06):
    print("I am starting the unification of Czech text contexts using Polars...")
    
    # --- 1. News Corpus (Hynky v2 - 1.6M+ lines) ---
    # We glue the title, annotation and the entire body of the article into one massive block
    df_news = pl.from_arrow(ds03["train"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    
    # --- 2. Legal / Alpaca dataset (czech-justice-summ-alpaca-long) ---
    # Here it makes sense to combine the instruction and the answer into one continuous text
    df_alpaca = pl.from_arrow(ds02["train"].data.table).lazy().select([
        (pl.col("instruction") + "\n" + pl.col("output")).alias("context"),
        pl.lit("alpaca_justice").alias("source")
    ])
    
    # --- 3. CERMAT Dataset (cermat_czech_mc) ---
    # Here we have the 'context' column, which we can enrich with a question
    df_cermat = pl.from_arrow(ds01["test"].data.table).lazy().select([
        (pl.col("context") + "\nOtázka: " + pl.col("query")).alias("context"),
        pl.lit("cermat").alias("source")
    ])

    # --- 4. Concatenation of all streams ---
    # Polars performs vertical joins extremely fast without unnecessary duplicate memory allocation
    unified_lazy = pl.concat([df_news, df_alpaca, df_cermat])
    
    # --- 5. Text extraction and cleaning + Calculation of logical predicates for JLNN ---
    final_df = unified_lazy.filter(
        pl.col("context").is_not_null() & (pl.col("context").str.len_chars() > 50)
    ).select([
        # Clean resulting text (context)
        pl.col("context"),
        pl.col("source"),
        
        # [PREDICT A]: Detection of masculine nouns in the text (Axiom of subject-predicate agreement)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["chlapci", "muži", "dělníci", "studenti", "hráči", "učitelé", "lidi", "psi"]
        ).cast(pl.Float32).alias("has_masc_animate"),
        
        # [PREDICATE C]: Detection of subordinating conjunctions introducing subordinate clauses (Axiom of Punctuation)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["že", "protože", "aby", "který", "jelikož", "jakmile", "zatímco"]
        ).cast(pl.Float32).alias("has_subord_conjunction"),
        
        # Auxiliary check: Is there a comma present in the text? (Basis for evaluating the t-norm)
        pl.col("context").str.contains(",").cast(pl.Float32).alias("has_comma")
    ]).collect()
    
    print(f"Unification complete! Total number of entire contexts in dataset: {final_df.height:,}")
    return final_df

In [17]:
%%time
df_dataset = build_unified_contexts(ds01, ds02, ds03, ds04, ds05, ds06)
df_dataset.sample(5)

I am starting the unification of Czech text contexts using Polars...
Unification complete! Total number of entire contexts in dataset: 1,646,599
CPU times: user 1min 1s, sys: 27.3 s, total: 1min 28s
Wall time: 1min 23s

shape: (5, 5)
┌─────────────────────────────────┬────────┬──────────────────┬────────────────────────┬───────────┐
│ context                         ┆ source ┆ has_masc_animate ┆ has_subord_conjunction ┆ has_comma │
│ ---                             ┆ ---    ┆ ---              ┆ ---                    ┆ ---       │
│ str                             ┆ str    ┆ f32              ┆ f32                    ┆ f32       │
╞═════════════════════════════════╪════════╪══════════════════╪════════════════════════╪═══════════╡
│ Zabil mačetou mladíka, trestán… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Na Starém bělidle vládla Babič… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Na oslavě 35. narozenin Copu z… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Fotbalové Brno teskní, na půl … ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Vodafone od srpna zruší studen… ┆ news   ┆ 1.0              ┆ 1.0                    ┆ 1.0       │
└─────────────────────────────────┴────────┴──────────────────┴────────────────────────┴───────────┘

### ***Preparing the RAW dataset (Pure sentence extraction in Polars)***

In [18]:
def create_raw_sentence_dataset(unified_df):
    print("I extract clean sentence segments and classify their punctuation...")
    
    # This regex finds any characters that end with either a period, question mark, exclamation mark, comma,
    # or at the end of the entire text. This will keep the sign right at the end of the segment!
    regex_segment_with_punc = r"[^.\?!,]+[\.\?!,]?"

    raw_segments = (
        unified_df
        # 1. We extract all the matching sentence segments as a Word List
        .select(
            pl.col("context").str.extract_all(regex_segment_with_punc)
        )
        # 2. Expand the sheet into separate rows
        .explode("context")
        .rename({"context": "segment"})
        
        # 3. We clean up spaces at the beginning and end (the stuck punctuation will remain)
        .with_columns(pl.col("segment").str.strip_chars())
        
        # 4. FILTERING: We remove empty or too short things
        .filter(
            (pl.col("segment").str.len_chars() > 5) & 
            (pl.col("segment").str.len_chars() < 200) &
            pl.col("segment").str.contains(r"[a-zA-Zá-žÁ-Ž]")
        )
        
        # 5. CLASSIFICATION OF TERMINAL TYPE
        .with_columns([
            pl.when(pl.col("segment").str.ends_with("?")).then(pl.lit("otazník"))
            .when(pl.col("segment").str.ends_with("!")).then(pl.lit("vykřičník"))
            .when(pl.col("segment").str.ends_with(".")).then(pl.lit("tečka"))
            .when(pl.col("segment").str.ends_with(",")).then(pl.lit("čárka"))
            .otherwise(pl.lit("žádná"))
            .alias("punctuation_type")
        ])
        
        # 6. Random sample for our Ollama
        .sample(n=10000, with_replacement=False, seed=42)
    )
    
    print(f"Prepared {raw_segments.height} sentence segments for Ollama.")
    return raw_segments

In [19]:
%%time
raw_sentence_df = create_raw_sentence_dataset(df_dataset)
raw_sentence_df.head(5)

I extract clean sentence segments and classify their punctuation...
Prepared 10000 sentence segments for Ollama.
CPU times: user 59.1 s, sys: 14.4 s, total: 1min 13s
Wall time: 1min 12s

shape: (5, 2)
┌─────────────────────────────────┬──────────────────┐
│ segment                         ┆ punctuation_type │
│ ---                             ┆ ---              │
│ str                             ┆ str              │
╞═════════════════════════════════╪══════════════════╡
│ Pokud se to stává opakovaně,    ┆ čárka            │
│ Připomeňte si letošní změny: R… ┆ čárka            │
│ Ani to však značku patřící pod… ┆ tečka            │
│ dopadly do moře                 ┆ čárka            │
│ Severní Korea …                 ┆                  │
│ „Někdy stačí i jen velká popel… ┆ čárka            │
└─────────────────────────────────┴──────────────────┘

### ***Export dataset***

In [20]:
def export_polars_to_pyarrow_dataset(polars_df, output_dir="processed_dataset"):
    print("Converting Polars DataFrame to PyArrow Table...")
    
    # We define a dictionary for translating Czech values ​​into English folder names
    translation_dict = {
        "otazník": "question_mark",
        "vykřičník": "exclamation_mark",
        "tečka": "period",
        "čárka": "comma",
        "žadná": "none"
    }
    
    # Temporarily add a column for folders in Polars and immediately convert to Arrow
    arrow_table = (
        polars_df
        .with_columns(
            pl.col("punctuation_type").replace(translation_dict).alias("folder_name")
        )
        .to_arrow()
    )
    
    print(f"PyArrow table ready. Number of rows: {arrow_table.num_rows:,}")
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Saving PyArrow Dataset to folder '{output_dir}' with English names...")
    
    # Writing to disk - partition will be done according to "folder_name" (English)
    ds.write_dataset(
        data=arrow_table,
        base_dir=output_dir,
        format="parquet",
        partitioning=["folder_name"],
        use_threads=True,
        existing_data_behavior="overwrite_or_ignore"
    )
    
    print("Export completed successfully!")

In [21]:
%%time
export_polars_to_pyarrow_dataset(raw_sentence_df, output_dir="raw_segments_dataset")

Converting Polars DataFrame to PyArrow Table...
PyArrow table ready. Number of rows: 10,000
Saving PyArrow Dataset to folder 'raw_segments_dataset' with English names...
Export completed successfully!
CPU times: user 28.3 ms, sys: 16.6 ms, total: 44.9 ms
Wall time: 64.7 ms