--------------------------------------------------
# **Create Czech text dataset for training**
-------------------------------------------------

In [1]:
!apt install git-lfs

git-lfs is already the newest version (3.0.2-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

## ***Imports***

In [2]:
import os, sys
import zipfile
import subprocess
import io
import shutil
import json
import polars as pl
import numpy as np
import pyarrow as pa
import pickle

import pyarrow.parquet as pq
import pyarrow.dataset as ds

from huggingface_hub import (
    get_full_repo_name,
    login,
    upload_folder,
    hf_hub_download,
    HfApi
)


from datasets import load_dataset
from kaggle_secrets import UserSecretsClient
from tqdm import tqdm

## ***Hugging Face Login***

In [3]:
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
user_email = user_secrets.get_secret("user_email")
user_name = user_secrets.get_secret("user_name")

login(token=hf_token)

### ***Data files***

1. ***CZLC/cermat_czech_mc***
   
   The **Cermat Czech MultiChoice** dataset was collected from assignments official CERMAT website. The dataset was collected from three tiers of assignments: 6 year, 9 year primary school test and final high school tests (so-called maturita). The assignments were semi-manually extracted from official PDFs available at [CERMAT's website](https://maturita.cermat.cz/menu/testy-a-zadani-z-predchozich-obdobi/matematika/testy-a-zadani-matematika).

    **Collection Date Range:** years 2016-2023

    ***Licensing and Credits***

    The majority of collection work was done by our student co-worker Jan Kapsa. Members of CZLC do not own the test assignments, neither are responsible for their contents.

    **Source:** https://huggingface.co/datasets/CZLC/cermat_czech_mc
 
2. ***hynky/czech-justice-summ-alpaca-long***

    **Source:** https://huggingface.co/datasets/hynky/czech-justice-summ-alpaca-long

3. ***hynky/czech_news_dataset_v2***

    Dataset containing the news articles from major online news outlets collected from 2000-2022.
    Follow-up paper https://arxiv.org/abs/2307.10666 (v1 of the dataset)

    Changes from v1:
        - Better contribution of novinky.cz in later stages
        - More articles, as a mistake in filtering was fixed.

   Collection was done using CmonCrawl.

   The dataset should be used for Research only purposes as I don't have rights for articles itself.

   **Source:** https://huggingface.co/datasets/hynky/czech_news_dataset_v2

4. ***davidadamczyk/czechbench_czech_news***

   This is a simplified and subsampled test subset from the original [czech_news_dataset_v2](https://huggingface.co/datasets/hynky/czech_news_dataset_v2).

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_czech_news

5. ***CIIRC-NLP/czech_news_simple-cs***

   **Source:** https://huggingface.co/datasets/CIIRC-NLP/czech_news_simple-cs

   This is a simplified and subsampled test subset from the original czech_news_dataset_v2.

   Only 5 basic news categories are considered:

   - Foreign
   - Local
   - Sports
   - Economy

   The test set includes 200 examples per category, 1000 examples in total. Apart from the category label, each example also contains the article's headline, brief summary, full textual content, optional keywords, original category specification, and URL.

   This dataset was created for use within the [Czech-Bench](https://gitlab.com/jirkoada/czech-bench) evaluation framework.

In [4]:
NUM_GENERATED_SAMPLES = 250000

In [5]:
ds01 = load_dataset("CZLC/cermat_czech_mc")
ds02 = load_dataset("hynky/czech-justice-summ-alpaca-long")
ds03 = load_dataset("hynky/czech_news_dataset_v2")
ds04 = load_dataset("davidadamczyk/czechbench_czech_news")
ds05 = load_dataset("CIIRC-NLP/czech_news_simple-cs", "default")

README.md: 0.00B [00:00, ?B/s]

test.jsonl: 0.00B [00:00, ?B/s]

Generating test split:   0%|          | 0/649 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/503 [00:00<?, ?B/s]

data/train-00000-of-00001-93f855e5cee8b5(…):   0%|          | 0.00/12.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4560 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00011-c758fbca39d29e(…):   0%|          | 0.00/285M [00:00<?, ?B/s]

data/train-00001-of-00011-04ed5181478f78(…):   0%|          | 0.00/283M [00:00<?, ?B/s]

data/train-00002-of-00011-7bab2e4f395098(…):   0%|          | 0.00/290M [00:00<?, ?B/s]

data/train-00003-of-00011-4f3be47507ad60(…):   0%|          | 0.00/300M [00:00<?, ?B/s]

data/train-00004-of-00011-eba4d38f0a5bd6(…):   0%|          | 0.00/317M [00:00<?, ?B/s]

data/train-00005-of-00011-1532bd3e35e037(…):   0%|          | 0.00/327M [00:00<?, ?B/s]

data/train-00006-of-00011-a90e9830da712d(…):   0%|          | 0.00/337M [00:00<?, ?B/s]

data/train-00007-of-00011-da6a604299b8e7(…):   0%|          | 0.00/328M [00:00<?, ?B/s]

data/train-00008-of-00011-2bd7fa9bb613ff(…):   0%|          | 0.00/312M [00:00<?, ?B/s]

data/train-00009-of-00011-2ccab243ff4f0d(…):   0%|          | 0.00/314M [00:00<?, ?B/s]

data/train-00010-of-00011-271947731579c0(…):   0%|          | 0.00/326M [00:00<?, ?B/s]

data/validation-00000-of-00002-d13428425(…):   0%|          | 0.00/173M [00:00<?, ?B/s]

data/validation-00001-of-00002-b8b386fb0(…):   0%|          | 0.00/175M [00:00<?, ?B/s]

data/test-00000-of-00002-9f5fef591354e92(…):   0%|          | 0.00/178M [00:00<?, ?B/s]

data/test-00001-of-00002-be0d3a48e095e91(…):   0%|          | 0.00/188M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1641471 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/144836 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/144837 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/92.9k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.64M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/980 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/test-00000-of-00001-8fd5c2a953da2a2(…):   0%|          | 0.00/2.67M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [6]:
print("ds01:",type(ds01),'\n',ds01,'\n')
print("ds02:",type(ds02),'\n',ds02,'\n')
print("ds03:",type(ds03),'\n',ds03,'\n')
print("ds04:",type(ds04),'\n',ds04,'\n')
print("ds05:",type(ds05),'\n',ds05,'\n')

ds01: <class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['type', 'query', 'choices', 'gold', 'context', 'subject', 'difficulty', 'source'],
        num_rows: 649
    })
})

ds02: <class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['output', 'instruction'],
        num_rows: 4560
    })
})

ds03: <class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 1641471
    })
    validation: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144836
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144837
    })
})

ds04: <class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 20
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 980
    })
})

ds05: <class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['url', 'headline', 'brief', 'keywords', 'category', 'content', 'category_unclean'],
        num_rows: 1000
    })
})

### ***We display data files in polars***

In [7]:
df01 = pl.from_arrow(ds01["test"].data.table)
df01.sample(5)

shape: (5, 8)
┌──────┬──────────────┬─────────────┬──────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ type ┆ query        ┆ choices     ┆ gold ┆ context     ┆ subject     ┆ difficulty  ┆ source      │
│ ---  ┆ ---          ┆ ---         ┆ ---  ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str  ┆ str          ┆ list[str]   ┆ i64  ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════╪══════════════╪═════════════╪══════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ MC   ┆ Ve kterém z  ┆ ["A. mám    ┆ 3    ┆ <bold>TEXT  ┆ český jazyk ┆ čtyřleté    ┆ 1. řádný    │
│      ┆ následujícíc ┆ horečku     ┆      ┆ 1           ┆ a           ┆ obory a     ┆ termín 2018 │
│      ┆ h úsek…      ┆ zlatou",    ┆      ┆ (1)</bold>  ┆ literatura  ┆ nástavbová  ┆             │
│      ┆              ┆ "B. …       ┆      ┆ Jdu s …     ┆             ┆ st…         ┆             │
│ MC   ┆ Ve kterém z  ┆ ["A. její   ┆ 0    ┆ <bold>Konec ┆ český jazyk ┆ maturitní   ┆ podzim 2022 │
│      ┆ následujícíc ┆ aktivity se ┆      ┆ chlapců,    ┆ a           ┆ zkouška     ┆             │
│      ┆ h úsek…      ┆ zaměřují…   ┆      ┆ dívek a s…  ┆ literatura  ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. V      ┆ 1    ┆ <bold>(1)</ ┆ český jazyk ┆ maturitní   ┆ podzim 2019 │
│      ┆ edujících    ┆ první části ┆      ┆ bold> <unde ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ výchozího   ┆      ┆ rline>Pr…   ┆ literatura  ┆             ┆             │
│      ┆              ┆ t…          ┆      ┆             ┆             ┆             ┆             │
│ MC   ┆ Ve kterém z  ┆ ["A.        ┆ 2    ┆ (1) Ve      ┆ český jazyk ┆ čtyřleté    ┆ 1. řádný    │
│      ┆ následujícíc ┆ starobylá   ┆      ┆ španělské   ┆ a           ┆ obory a     ┆ termín 2022 │
│      ┆ h úsek…      ┆ tradice má  ┆      ┆ vesničce    ┆ literatura  ┆ nástavbová  ┆             │
│      ┆              ┆ ovše…       ┆      ┆ Cast…       ┆             ┆ st…         ┆             │
│ MC   ┆ Které z násl ┆ ["A. Ve     ┆ 2    ┆ <bold>TEXT  ┆ český jazyk ┆ maturitní   ┆ jaro 2018   │
│      ┆ edujících    ┆ stejné době ┆      ┆ 1           ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ jako on tv… ┆      ┆ Les Ballets ┆ literatura  ┆             ┆             │
│      ┆              ┆             ┆      ┆ Buben…      ┆             ┆             ┆             │
└──────┴──────────────┴─────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [8]:
df02 = pl.from_arrow(ds03["train"].data.table)
df02.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Francouzs ┆ Francouzs ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2012-09- │
│ ww.novink ┆           ┆ ký        ┆ ký        ┆   ┆           ┆           ┆           ┆ 19       │
│ y.cz/zahr ┆           ┆ satirický ┆ satirický ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ani…      ┆           ┆ magazín … ┆ magazín … ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Ivan    ┆ Bush má   ┆ Americký  ┆ … ┆ [1]       ┆ 1         ┆ 5         ┆ 2005-02- │
│ ww.novink ┆ Vilček"]  ┆ promluvit ┆ prezident ┆   ┆           ┆           ┆           ┆ 11       │
│ y.cz/zahr ┆           ┆ ke        ┆ George W. ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ani…      ┆           ┆ Slovákům  ┆ B…        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://b ┆ ["Jakub   ┆ KRÁTCE: V ┆ Loučení   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2019-08- │
│ erounsky. ┆ Šťástka"] ┆ Hořovicíc ┆ se prázdn ┆   ┆           ┆           ┆           ┆ 28       │
│ denik.cz/ ┆           ┆ h se      ┆ inami je  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zpr…      ┆           ┆ rozlou…   ┆ přic…     ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Helena  ┆ Mimo tři  ┆ Nové      ┆ … ┆ [2]       ┆ 2         ┆ 4         ┆ 2019-08- │
│ darsky.de ┆ Zelená    ┆ stanovená ┆ Město na  ┆   ┆           ┆           ┆           ┆ 15       │
│ nik.cz/zp ┆ Křížová"] ┆ místa a   ┆ Moravě –  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ rav…      ┆           ┆ čas…      ┆ Novoměs…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milan   ┆ Za cestu  ┆ Evropané  ┆ … ┆ [1, 1]    ┆ 1         ┆ 4         ┆ 2009-09- │
│ ww.irozhl ┆ Kopp",    ┆ do        ┆ by měli   ┆   ┆           ┆           ┆           ┆ 10       │
│ as.cz/zpr ┆ "Ondřej   ┆ Spojených ┆ za cestu  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ avy…      ┆ Houska"…  ┆ států mo… ┆ do S…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df03_train = pl.from_arrow(ds03["train"].data.table)
df03_train.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Dělohy    ┆ Ve        ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2012-09- │
│ ww.novink ┆           ┆ dvou      ┆ Švédsku   ┆   ┆           ┆           ┆           ┆ 18       │
│ y.cz/zahr ┆           ┆ matek tra ┆ byly u    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ani…      ┆           ┆ nsplantov ┆ dvou      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆ mladých…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Soudy s   ┆ Krajský   ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2020-01- │
│ ww.novink ┆           ┆ podmíněný ┆ soud v    ┆   ┆           ┆           ┆           ┆ 15       │
│ y.cz/doma ┆           ┆ m propušt ┆ Plzni     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ci/…      ┆           ┆ ěním…     ┆ minulý    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tý…       ┆   ┆           ┆           ┆           ┆          │
│ https://s ┆ ["Vladimí ┆ Hlasování ┆ Karlovars ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2017-06- │
│ okolovsky ┆ r         ┆ o         ┆ ký kraj – ┆   ┆           ┆           ┆           ┆ 07       │
│ .denik.cz ┆ Meluzín"] ┆ „stavbu“  ┆ Do finále ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /z-…      ┆           ┆ ukazuje,  ┆ s…        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://m ┆ ["Václav  ┆ „Snad     ┆ Litvínov  ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2018-10- │
│ ostecky.d ┆ Veverka"] ┆ jednou    ┆ /ROZHOVOR ┆   ┆           ┆           ┆           ┆ 03       │
│ enik.cz/h ┆           ┆ porodím v ┆ / –       ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ oke…      ┆           ┆ den, kd…  ┆ Eliška B… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Simona  ┆ Tři 'Gent ┆ Chrudimsk ┆ … ┆ [2, 1]    ┆ 3         ┆ 4         ┆ 2013-05- │
│ ww.irozhl ┆ Bartošová ┆ lemani    ┆ o má tři  ┆   ┆           ┆           ┆           ┆ 16       │
│ as.cz/reg ┆ ", "Josef ┆ silnic' z ┆ nové      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ion…      ┆ Ko…       ┆ Chru…     ┆ Gentlem…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df03_validation = pl.from_arrow(ds03["validation"].data.table)
df03_validation.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://k ┆ ["Daniela ┆ Nový      ┆ Obyvatele ┆ … ┆ [2]       ┆ 2         ┆ 5         ┆ 2020-06- │
│ latovsky. ┆ Loudová"] ┆ poldr     ┆ Lub,      ┆   ┆           ┆           ┆           ┆ 26       │
│ denik.cz/ ┆           ┆ zabrání   ┆ kterým    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zpr…      ┆           ┆ zatopení  ┆ každý vě… ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ za…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milan   ┆ Tragédie: ┆ /FOTOGALE ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2021-01- │
│ ww.denik. ┆ Holakovsk ┆ Zaparkova ┆ RIE/      ┆   ┆           ┆           ┆           ┆ 13       │
│ cz/nehody ┆ ý"]       ┆ ný kamion ┆ Život     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /tr…      ┆           ┆ s…        ┆ řidiče    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ kam…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jiří    ┆ Místo     ┆ Ve 30.    ┆ … ┆ [1]       ┆ 1         ┆ 7         ┆ 2020-05- │
│ ww.seznam ┆ Hošek"]   ┆ medailí   ┆ letech    ┆   ┆           ┆           ┆           ┆ 10       │
│ zpravy.cz ┆           ┆ zákopy a  ┆ jim u     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /cl…      ┆           ┆ kulka. …  ┆ nohou     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ leže…     ┆   ┆           ┆           ┆           ┆          │
│ https://s ┆ []        ┆ Dočasná   ┆ Fotbalové ┆ … ┆ []        ┆ 0         ┆ 5         ┆ 2020-05- │
│ port.aktu ┆           ┆ revoluce  ┆ týmy      ┆   ┆           ┆           ┆           ┆ 08       │
│ alne.cz/f ┆           ┆ ve        ┆ budou     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ otb…      ┆           ┆ fotbale.  ┆ moci      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ T…        ┆ vzhl…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jiří    ┆ Bundeslig ┆ Původně   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2020-09- │
│ ww.idnes. ┆ Punčochář ┆ a mezi    ┆ to        ┆   ┆           ┆           ┆           ┆ 16       │
│ cz/fotbal ┆ "]        ┆ kukuřicí. ┆ vypadlo   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /do…      ┆           ┆ Fano…     ┆ jako      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ vtip. …   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df03_test = pl.from_arrow(ds03["test"].data.table)
df03_test.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ ["Jitka   ┆ Na        ┆ Hromadné  ┆ … ┆ [2, 2]    ┆ 2         ┆ 4         ┆ 2021-02- │
│ ww.idnes. ┆ Šrámková" ┆ Tachovsku ┆ testování ┆   ┆           ┆           ┆           ┆ 18       │
│ cz/plzen/ ┆ , "Valent ┆ začne     ┆ ve        ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zpr…      ┆ ýna …     ┆ testování ┆ firmách,… ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ v…        ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Dívka ze  ┆ Zoe       ┆ … ┆ []        ┆ 0         ┆ 5         ┆ 2021-05- │
│ ww.idnes. ┆           ┆ slavného  ┆ Rothová   ┆   ┆           ┆           ┆           ┆ 14       │
│ cz/revue/ ┆           ┆ memu      ┆ (21)      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ spo…      ┆           ┆ prodala…  ┆ prodala   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ svou …    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Tomáš   ┆ Žák je v  ┆ Kantoři   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2021-12- │
│ ww.idnes. ┆ Matoušek" ┆ karanténě ┆ učí podle ┆   ┆           ┆           ┆           ┆ 01       │
│ cz/zpravy ┆ ]         ┆ , ale     ┆ svého     ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /do…      ┆           ┆ rodiče…   ┆ běžnéh…   ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ []        ┆ Zavazadla ┆ V pondělí ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2021-04- │
│ pravy.akt ┆           ┆ vyhoštěný ┆ odpoledne ┆   ┆           ┆           ┆           ┆ 20       │
│ ualne.cz/ ┆           ┆ ch Rusů   ┆ odlétlo   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ dom…      ┆           ┆ zap…      ┆ os…       ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Kroměříž  ┆ Kroměřížs ┆ … ┆ []        ┆ 0         ┆ 4         ┆ 2022-06- │
│ ww.seznam ┆           ┆ zahájila  ┆ ká        ┆   ┆           ┆           ┆           ┆ 02       │
│ zpravy.cz ┆           ┆ ostrý     ┆ radnice   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /cl…      ┆           ┆ provoz…   ┆ zahájila  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ o…        ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df04_train = pl.from_arrow(ds04["train"].data.table)
df04_train.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Ministers ┆ Ministers ┆ … ┆ 3         ┆ 2021-02-2 ┆ 2         ┆ 180      │
│ ww.irozhl ┆           ┆ tvo       ┆ tvo       ┆   ┆           ┆ 4         ┆           ┆          │
│ as.cz/zpr ┆           ┆ poslalo   ┆ školství  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ avy…      ┆           ┆ ředitelům ┆ poslalo … ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://s ┆ ["Mirosla ┆ Nájezdový ┆ Kádr      ┆ … ┆ 7         ┆ 2022-05-1 ┆ 3         ┆ 140      │
│ umpersky. ┆ v Pergl"] ┆ specialis ┆ Draků pro ┆   ┆           ┆ 5         ┆           ┆          │
│ denik.cz/ ┆           ┆ ta a      ┆ nadcházej ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ hok…      ┆           ┆ perspe…   ┆ ící pr…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jiří    ┆ PŘEHLEDNĚ ┆ Stát od   ┆ … ┆ 4         ┆ 2022-06-2 ┆ 7         ┆ 10       │
│ ww.denik. ┆ Janda"]   ┆ : 500     ┆ příštího  ┆   ┆           ┆ 3         ┆           ┆          │
│ cz/ekonom ┆           ┆ korun k   ┆ roku      ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ důchodu…  ┆ přilepší… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Martin  ┆ Vizita:   ┆ Britský   ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2         ┆ 131      │
│ ww.seznam ┆ Čaban"]   ┆ Jak pošťo ┆ vědecký   ┆   ┆           ┆ 8         ┆           ┆          │
│ zpravy.cz ┆           ┆ uchnout k ┆ časopis   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ očk…      ┆ Nature…   ┆   ┆           ┆           ┆           ┆          │
│ https://d ┆ ["Jarosla ┆ Sportovci ┆ Pandemie  ┆ … ┆ 5         ┆ 2021-05-0 ┆ 3         ┆ 32       │
│ ecinsky.d ┆ v Zeman"] ┆ z         ┆ koronavir ┆   ┆           ┆ 7         ┆           ┆          │
│ enik.cz/o ┆           ┆ Děčínska  ┆ u v Česku ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ sta…      ┆           ┆ se        ┆ us…       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ zlobí!…   ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
df04_test = pl.from_arrow(ds04["test"].data.table)
df04_test.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Na D2 se  ┆ Nehoda    ┆ … ┆ 4         ┆ 2022-06-2 ┆ 2         ┆ 115      │
│ ww.idnes. ┆           ┆ u Blučiny ┆ dvou nákl ┆   ┆           ┆ 3         ┆           ┆          │
│ cz/brno/z ┆           ┆ srazily   ┆ adních    ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ pra…      ┆           ┆ kam…      ┆ vozů dn…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Fotbalist ┆ Fotbalist ┆ … ┆ 6         ┆ 2021-03-2 ┆ 3         ┆ 17       │
│ ww.idnes. ┆           ┆ é         ┆ é         ┆   ┆           ┆ 7         ┆           ┆          │
│ cz/fotbal ┆           ┆ Jablonce  ┆ Jablonce  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /do…      ┆           ┆ přešli v  ┆ vyhráli v ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ d…        ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ []        ┆ "Vyléčíme ┆ Uplynulý  ┆ … ┆ 3         ┆ 2021-03-0 ┆ 7         ┆ 97       │
│ pravy.akt ┆           ┆ cokoliv." ┆ rok s kor ┆   ┆           ┆ 3         ┆           ┆          │
│ ualne.cz/ ┆           ┆ Řada      ┆ onavirem  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ eko…      ┆           ┆ e-sho…    ┆ ovl…      ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Dominik ┆ Seychely  ┆ Seychely  ┆ … ┆ 3         ┆ 2021-05-1 ┆ 1         ┆ 148      │
│ pravy.akt ┆ a Perlíno ┆ naočkoval ┆ naočkoval ┆   ┆           ┆ 2         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ y většinu ┆ y         ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ zah…      ┆           ┆ li…       ┆ největší  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ č…        ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Jana    ┆ Když mu   ┆ V srpnu   ┆ … ┆ 2         ┆ 2021-07-1 ┆ 1         ┆ 23       │
│ pravy.akt ┆ Václavíko ┆ došly     ┆ 1997 si   ┆   ┆           ┆ 3         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ peníze,   ┆ dvouapůll ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ zah…      ┆           ┆ žebral. … ┆ etý K…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df05 = pl.from_arrow(ds05["test"].data.table)
df05.sample(5)

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────┬─────────────┬─────────────┐
│ url          ┆ headline     ┆ brief        ┆ keywords     ┆ category ┆ content     ┆ category_un │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---      ┆ ---         ┆ clean       │
│ str          ┆ str          ┆ str          ┆ list[str]    ┆ i64      ┆ str         ┆ ---         │
│              ┆              ┆              ┆              ┆          ┆             ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════╪═════════════╪═════════════╡
│ https://www. ┆ Lanovky v    ┆ Lanovky ve   ┆ ["Krkonoše", ┆ 2        ┆ Opět se     ┆ Regiony     │
│ seznamzpravy ┆ Krkonoších   ┆ střediscích  ┆ "Lanovka",   ┆          ┆ lanovky v   ┆             │
│ .cz/cl…      ┆ mimo prov…   ┆ Krkonoš…     ┆ "Turis…      ┆          ┆ Krkonoších  ┆             │
│              ┆              ┆              ┆              ┆          ┆ n…          ┆             │
│ https://www. ┆ Glosa: Další ┆ Rozmohl se   ┆ ["Prezidents ┆ 2        ┆ Po Karlu    ┆ Volby       │
│ seznamzpravy ┆ nudící se    ┆ nám tu       ┆ ké volby",   ┆          ┆ Janečkovi   ┆             │
│ .cz/cl…      ┆ miliard…     ┆ takový       ┆ "Tomáš …     ┆          ┆ oznámil ve  ┆             │
│              ┆              ┆ nešva…       ┆              ┆          ┆ …           ┆             │
│ https://maga ┆ Velvyslanec  ┆ Herec a      ┆ ["Klasická   ┆ 4        ┆ Šestašedesá ┆ Klasická    │
│ zin.aktualne ┆ koupil zámek ┆ zpěvák       ┆ hudba",      ┆          ┆ tiletý      ┆ hudba       │
│ .cz/ku…      ┆ i se …       ┆ Ondřej       ┆ "Kultura", … ┆          ┆ Havelka s   ┆             │
│              ┆              ┆ Havelka …    ┆              ┆          ┆ os…         ┆             │
│ https://www. ┆ Ozvěny       ┆ Čtyři        ┆ []           ┆ 4        ┆ „Filmový    ┆ Kultura     │
│ novinky.cz/k ┆ Ji.hlavy     ┆ desítky      ┆              ┆          ┆ svět se     ┆             │
│ ultura…      ┆ nabídnou     ┆ filmů z      ┆              ┆          ┆ kvůli       ┆             │
│              ┆ čtyři…       ┆ loňského…    ┆              ┆          ┆ pandemi…    ┆             │
│ https://www. ┆ RECENZE:     ┆ Během roku   ┆ ["Ivan       ┆ 4        ┆ Filmař,     ┆ Kultura     │
│ idnes.cz/kul ┆ Čtenář má    ┆ nachodil po  ┆ fíla",       ┆          ┆ spisovatel  ┆             │
│ tura/l…      ┆ chuť poděko… ┆ nejvyšš…     ┆ "Jeseníky",  ┆          ┆ a fotograf  ┆             │
│              ┆              ┆              ┆ … "J…        ┆          ┆ …           ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────┴─────────────┴─────────────┘

### ***Creating a summary data file***

In [15]:
def build_unified_contexts(ds01, ds02, ds03, ds04, ds05):
    print("I am starting the unification of Czech text contexts using Polars...")
    
    # --- 1. News Corpus (Hynky v2 - 1.6M+ lines) ---
    # We glue the title, annotation and the entire body of the article into one massive block
    df_news_A = pl.from_arrow(ds03["train"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    df_news_B = pl.from_arrow(ds03["validation"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    df_news_C = pl.from_arrow(ds03["test"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])

    # --- 2. davidadamczyk/czechbench_czech_news ---
    df_news_D = pl.from_arrow(ds04["train"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    df_news_E = pl.from_arrow(ds04["test"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])

    # --- 3. CIIRC-NLP/czech_news_simple-cs ---
    df_news_F = pl.from_arrow(ds05["test"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    
    # --- 4. Legal / Alpaca dataset (czech-justice-summ-alpaca-long) ---
    # Here it makes sense to combine the instruction and the answer into one continuous text
    df_alpaca = pl.from_arrow(ds02["train"].data.table).lazy().select([
        (pl.col("instruction") + "\n" + pl.col("output")).alias("context"),
        pl.lit("alpaca_justice").alias("source")
    ])
    
    # --- 5. CERMAT Dataset (cermat_czech_mc) ---
    # Here we have the 'context' column, which we can enrich with a question
    df_cermat = pl.from_arrow(ds01["test"].data.table).lazy().select([
        (pl.col("context") + "\nOtázka: " + pl.col("query")).alias("context"),
        pl.lit("cermat").alias("source")
    ])

    # --- 6. Concatenation of all streams ---
    # Polars performs vertical joins extremely fast without unnecessary duplicate memory allocation
    unified_lazy = pl.concat([df_news_A, df_news_B, df_news_C, df_news_D, df_news_E, df_news_F, df_alpaca, df_cermat])
    
    # --- 7. Text extraction and cleaning + Calculation of logical predicates for JLNN ---
    final_df = unified_lazy.filter(
        pl.col("context").is_not_null() & (pl.col("context").str.len_chars() > 50)
    ).select([
        # Clean resulting text (context)
        pl.col("context"),
        pl.col("source"),
        
        # [PREDICT A]: Detection of masculine nouns in the text (Axiom of subject-predicate agreement)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["chlapci", "muži", "dělníci", "studenti", "hráči", "učitelé", "lidi", "psi"]
        ).cast(pl.Float32).alias("has_masc_animate"),
        
        # [PREDICATE C]: Detection of subordinating conjunctions introducing subordinate clauses (Axiom of Punctuation)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["že", "protože", "aby", "který", "jelikož", "jakmile", "zatímco"]
        ).cast(pl.Float32).alias("has_subord_conjunction"),
        
        # Auxiliary check: Is there a comma present in the text? (Basis for evaluating the t-norm)
        pl.col("context").str.contains(",").cast(pl.Float32).alias("has_comma")
    ]).collect()
    
    print(f"Unification complete! Total number of entire contexts in dataset: {final_df.height:,}")
    return final_df

In [16]:
%%time
df_dataset = build_unified_contexts(ds01, ds02, ds03, ds04, ds05)
df_dataset.sample(5)

I am starting the unification of Czech text contexts using Polars...
Unification complete! Total number of entire contexts in dataset: 1,938,272
CPU times: user 1min 37s, sys: 23.6 s, total: 2min
Wall time: 1min 48s

shape: (5, 5)
┌─────────────────────────────────┬────────┬──────────────────┬────────────────────────┬───────────┐
│ context                         ┆ source ┆ has_masc_animate ┆ has_subord_conjunction ┆ has_comma │
│ ---                             ┆ ---    ┆ ---              ┆ ---                    ┆ ---       │
│ str                             ┆ str    ┆ f32              ┆ f32                    ┆ f32       │
╞═════════════════════════════════╪════════╪══════════════════╪════════════════════════╪═══════════╡
│ Majovák zahrál v Karviné Novor… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ RECENZE: V přetěžké úloze Kňaž… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Kotík nabídl výjimečný zážitek… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Petanque v zimě? Proč by ne...… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Na Jižní spojce se srazilo aut… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
└─────────────────────────────────┴────────┴──────────────────┴────────────────────────┴───────────┘

In [17]:
df_dataset.shape

(1938272, 5)

### ***Preparing the RAW dataset (Pure sentence extraction in Polars)***

In [18]:
def create_raw_sentence_dataset(unified_df):
    print("I extract clean sentence segments and classify their punctuation...")
    
    # This regex finds any characters that end with either a period, question mark, exclamation mark, comma,
    # or at the end of the entire text. This will keep the sign right at the end of the segment!
    regex_segment_with_punc = r"[^.\?!,]+[\.\?!,]?"

    raw_segments = (
        unified_df
        # 1. We extract all the matching sentence segments as a Word List
        .select(
            pl.col("context").str.extract_all(regex_segment_with_punc)
        )
        # 2. Expand the sheet into separate rows
        .explode("context")
        .rename({"context": "segment"})
        
        # 3. We clean up spaces at the beginning and end (the stuck punctuation will remain)
        .with_columns(pl.col("segment").str.strip_chars())
        
        # 4. FILTERING: We remove empty or too short things
        .filter(
            (pl.col("segment").str.len_chars() > 5) & 
            (pl.col("segment").str.len_chars() < 200) &
            pl.col("segment").str.contains(r"[a-zA-Zá-žÁ-Ž]")
        )
        
        # 5. CLASSIFICATION OF TERMINAL TYPE
        .with_columns([
            pl.when(pl.col("segment").str.ends_with("?")).then(pl.lit("otazník"))
            .when(pl.col("segment").str.ends_with("!")).then(pl.lit("vykřičník"))
            .when(pl.col("segment").str.ends_with(".")).then(pl.lit("tečka"))
            .when(pl.col("segment").str.ends_with(",")).then(pl.lit("čárka"))
            .otherwise(pl.lit("žádná"))
            .alias("punctuation_type")
        ])
        
        # 6. Random sample
        .sample(n=NUM_GENERATED_SAMPLES, with_replacement=False, seed=42)
    )
    
    print(f"Prepared {raw_segments.height} sentence segments.")
    return raw_segments

In [19]:
%%time
raw_sentence_df = create_raw_sentence_dataset(df_dataset)
raw_sentence_df.head(5)

I extract clean sentence segments and classify their punctuation...
Prepared 250000 sentence segments.
CPU times: user 2min 19s, sys: 13.3 s, total: 2min 33s
Wall time: 2min 9s

shape: (5, 2)
┌─────────────────────────────────┬──────────────────┐
│ segment                         ┆ punctuation_type │
│ ---                             ┆ ---              │
│ str                             ┆ str              │
╞═════════════════════════════════╪══════════════════╡
│ Učinily zásadní krok k záchran… ┆ tečka            │
│ Úřad práce,                     ┆ čárka            │
│ že podle vypracovaného modelu … ┆ tečka            │
│ Podporu rozpočtu naopak vyjádř… ┆ tečka            │
│ Foto: Miroslav Homola,          ┆ čárka            │
└─────────────────────────────────┴──────────────────┘

In [20]:
raw_sentence_df.shape

(250000, 2)

### ***Export dataset***

In [21]:
def export_polars_to_pyarrow_dataset(polars_df, output_dir="processed_dataset"):
    print("Converting Polars DataFrame to PyArrow Table...")
    
    # We define a dictionary for translating Czech values into English folder names
    translation_dict = {
        "otazník": "question_mark",
        "vykřičník": "exclamation_mark",
        "tečka": "period",
        "čárka": "comma",
        "žádná": "none"
    }
    
    # Temporarily add a column for folders in Polars and immediately convert to Arrow
    arrow_table = (
        polars_df
        .with_columns(
            pl.col("punctuation_type").replace(translation_dict).alias("folder_name")
        )
        .to_arrow()
    )
    
    print(f"PyArrow table ready. Number of rows: {arrow_table.num_rows:,}")
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Saving PyArrow Dataset to folder '{output_dir}' with English names...")
    
    # Writing to disk - partition will be done according to "folder_name" (English)
    ds.write_dataset(
        data=arrow_table,
        base_dir=output_dir,
        format="parquet",
        partitioning=["folder_name"],
        use_threads=True,
        existing_data_behavior="overwrite_or_ignore"
    )
    
    print("Export completed successfully!")

In [22]:
%%time
export_polars_to_pyarrow_dataset(raw_sentence_df, output_dir="raw_segments_dataset")

Converting Polars DataFrame to PyArrow Table...
PyArrow table ready. Number of rows: 250,000
Saving PyArrow Dataset to folder 'raw_segments_dataset' with English names...
Export completed successfully!
CPU times: user 287 ms, sys: 68.9 ms, total: 356 ms
Wall time: 192 ms