--------------------------------------------------
# **Create Czech text dataset for training**
-------------------------------------------------

In [1]:
!apt install git-lfs

git-lfs is already the newest version (3.0.2-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

## ***Imports***

In [2]:
import os, sys
import zipfile
import subprocess
import io
import shutil
import json
import polars as pl
import numpy as np
import pyarrow as pa
import pickle

import pyarrow.parquet as pq
import pyarrow.dataset as ds

from huggingface_hub import (
    get_full_repo_name,
    login,
    upload_folder,
    hf_hub_download,
    HfApi
)


from datasets import load_dataset
from kaggle_secrets import UserSecretsClient
from tqdm import tqdm

## ***Hugging Face Login***

In [3]:
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
user_email = user_secrets.get_secret("user_email")
user_name = user_secrets.get_secret("user_name")

login(token=hf_token)

### ***Data files***

1. ***CZLC/cermat_czech_mc***
   
   The **Cermat Czech MultiChoice** dataset was collected from assignments official CERMAT website. The dataset was collected from three tiers of assignments: 6 year, 9 year primary school test and final high school tests (so-called maturita). The assignments were semi-manually extracted from official PDFs available at [CERMAT's website](https://maturita.cermat.cz/menu/testy-a-zadani-z-predchozich-obdobi/matematika/testy-a-zadani-matematika).

    **Collection Date Range:** years 2016-2023

    ***Licensing and Credits***

    The majority of collection work was done by our student co-worker Jan Kapsa. Members of CZLC do not own the test assignments, neither are responsible for their contents.

    **Source:** https://huggingface.co/datasets/CZLC/cermat_czech_mc
 
2. ***hynky/czech-justice-summ-alpaca-long***

    **Source:** https://huggingface.co/datasets/hynky/czech-justice-summ-alpaca-long

3. ***hynky/czech_news_dataset_v2***

    Dataset containing the news articles from major online news outlets collected from 2000-2022.
    Follow-up paper https://arxiv.org/abs/2307.10666 (v1 of the dataset)

    Changes from v1:
        - Better contribution of novinky.cz in later stages
        - More articles, as a mistake in filtering was fixed.

   Collection was done using CmonCrawl.

   The dataset should be used for Research only purposes as I don't have rights for articles itself.

   **Source:** https://huggingface.co/datasets/hynky/czech_news_dataset_v2

4. ***davidadamczyk/czechbench_agree***

   This is an adapted and filtered test subset from the original Czech grammar agreement dataset

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_agree

6. ***davidadamczyk/czechbench_czech_news***

   This is a simplified and subsampled test subset from the original [czech_news_dataset_v2](https://huggingface.co/datasets/hynky/czech_news_dataset_v2).

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_czech_news

8. ***CIIRC-NLP/czech_news_simple-cs***

   **Source:** https://huggingface.co/datasets/CIIRC-NLP/czech_news_simple-cs

   This is a simplified and subsampled test subset from the original czech_news_dataset_v2.

   Only 5 basic news categories are considered:

   - Foreign
   - Local
   - Sports
   - Economy

   The test set includes 200 examples per category, 1000 examples in total. Apart from the category label, each example also contains the article's headline, brief summary, full textual content, optional keywords, original category specification, and URL.

   This dataset was created for use within the [Czech-Bench](https://gitlab.com/jirkoada/czech-bench) evaluation framework.

In [4]:
ds01 = load_dataset("CZLC/cermat_czech_mc")
ds02 = load_dataset("hynky/czech-justice-summ-alpaca-long")
ds03 = load_dataset("hynky/czech_news_dataset_v2")
ds04 = load_dataset("davidadamczyk/czechbench_agree")
ds05 = load_dataset("davidadamczyk/czechbench_czech_news")
ds06 = load_dataset("CIIRC-NLP/czech_news_simple-cs", "default")

README.md: 0.00B [00:00, ?B/s]

test.jsonl: 0.00B [00:00, ?B/s]

Generating test split:   0%|          | 0/649 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/503 [00:00<?, ?B/s]

data/train-00000-of-00001-93f855e5cee8b5(…):   0%|          | 0.00/12.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4560 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00011-c758fbca39d29e(…):   0%|          | 0.00/285M [00:00<?, ?B/s]

data/train-00001-of-00011-04ed5181478f78(…):   0%|          | 0.00/283M [00:00<?, ?B/s]

data/train-00002-of-00011-7bab2e4f395098(…):   0%|          | 0.00/290M [00:00<?, ?B/s]

data/train-00003-of-00011-4f3be47507ad60(…):   0%|          | 0.00/300M [00:00<?, ?B/s]

data/train-00004-of-00011-eba4d38f0a5bd6(…):   0%|          | 0.00/317M [00:00<?, ?B/s]

data/train-00005-of-00011-1532bd3e35e037(…):   0%|          | 0.00/327M [00:00<?, ?B/s]

data/train-00006-of-00011-a90e9830da712d(…):   0%|          | 0.00/337M [00:00<?, ?B/s]

data/train-00007-of-00011-da6a604299b8e7(…):   0%|          | 0.00/328M [00:00<?, ?B/s]

data/train-00008-of-00011-2bd7fa9bb613ff(…):   0%|          | 0.00/312M [00:00<?, ?B/s]

data/train-00009-of-00011-2ccab243ff4f0d(…):   0%|          | 0.00/314M [00:00<?, ?B/s]

data/train-00010-of-00011-271947731579c0(…):   0%|          | 0.00/326M [00:00<?, ?B/s]

data/validation-00000-of-00002-d13428425(…):   0%|          | 0.00/173M [00:00<?, ?B/s]

data/validation-00001-of-00002-b8b386fb0(…):   0%|          | 0.00/175M [00:00<?, ?B/s]

data/test-00000-of-00002-9f5fef591354e92(…):   0%|          | 0.00/178M [00:00<?, ?B/s]

data/test-00001-of-00002-be0d3a48e095e91(…):   0%|          | 0.00/188M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1641471 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/144836 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/144837 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/4.27k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/607 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/92.9k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.64M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/980 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/test-00000-of-00001-8fd5c2a953da2a2(…):   0%|          | 0.00/2.67M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [5]:
print(type(ds01),'\n',ds01)
print(type(ds02),'\n',ds02)
print(type(ds03),'\n',ds03)
print(type(ds04),'\n',ds04)
print(type(ds05),'\n',ds05)
print(type(ds06),'\n',ds06)

<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['type', 'query', 'choices', 'gold', 'context', 'subject', 'difficulty', 'source'],
        num_rows: 649
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['output', 'instruction'],
        num_rows: 4560
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 1641471
    })
    validation: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144836
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144837
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 20
    })
    test: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 607
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 20
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 980
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['url', 'headline', 'brief', 'keywords', 'category', 'content', 'category_unclean'],
        num_rows: 1000
    })
})

### ***We display data files in polars***

In [6]:
df01 = pl.from_arrow(ds01["test"].data.table)
df01.sample(5)

shape: (5, 8)
┌──────┬──────────────┬─────────────┬──────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ type ┆ query        ┆ choices     ┆ gold ┆ context     ┆ subject     ┆ difficulty  ┆ source      │
│ ---  ┆ ---          ┆ ---         ┆ ---  ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str  ┆ str          ┆ list[str]   ┆ i64  ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════╪══════════════╪═════════════╪══════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ MC   ┆ Ve kterém z  ┆ ["A. ty se  ┆ 0    ┆ Když se     ┆ český jazyk ┆ šestiletá   ┆ 3. řádný    │
│      ┆ následujícíc ┆ zadem       ┆      ┆ Prcek       ┆ a           ┆ gymnázia    ┆ termín 2022 │
│      ┆ h úsek…      ┆ dostaneš    ┆      ┆ vrátil ze   ┆ literatura  ┆             ┆             │
│      ┆              ┆ domů…       ┆      ┆ zajetí…     ┆             ┆             ┆             │
│ MC   ┆ Která z násl ┆ ["A. Nejdůl ┆ 2    ┆ null        ┆ český jazyk ┆ šestiletá   ┆ 1. řádný    │
│      ┆ edujících    ┆ ežitější    ┆      ┆             ┆ a           ┆ gymnázia    ┆ termín 2022 │
│      ┆ vět není…    ┆ kontakty m… ┆      ┆             ┆ literatura  ┆             ┆             │
│ MC   ┆ Ve kterém z  ┆ ["A. krutá  ┆ 3    ┆ Robin Hood  ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ následujícíc ┆ zkáza ale   ┆      ┆ kráčel po   ┆ a           ┆ gymnázia    ┆ termín 2022 │
│      ┆ h úsek…      ┆ nepřítele…  ┆      ┆ stezce Sh…  ┆ literatura  ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. Chybně ┆ 1    ┆ <bold>(1)</ ┆ český jazyk ┆ maturitní   ┆ podzim 2022 │
│      ┆ edujících    ┆ užité slovo ┆      ┆ bold>       ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ laik b…     ┆      ┆ Vexilologie ┆ literatura  ┆             ┆             │
│      ┆              ┆             ┆      ┆ s…          ┆             ┆             ┆             │
│ MC   ┆ Která z násl ┆ ["A.        ┆ 0    ┆ Zvláštní    ┆ český jazyk ┆ maturitní   ┆ jaro 2019   │
│      ┆ edujících    ┆ informace,  ┆      ┆ způsob, jak ┆ a           ┆ zkouška     ┆             │
│      ┆ informac…    ┆ že s        ┆      ┆ skrýt obs…  ┆ literatura  ┆             ┆             │
│      ┆              ┆ nápadem n…  ┆      ┆             ┆             ┆             ┆             │
└──────┴──────────────┴─────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
df02 = pl.from_arrow(ds03["train"].data.table)
df02.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ ["Bibiana ┆ Plus size ┆ Plus size ┆ … ┆ [2]       ┆ 2         ┆ 4         ┆ 2016-11- │
│ ww.idnes. ┆ Martina   ┆ modelka   ┆ modelka   ┆   ┆           ┆           ┆           ┆ 03       │
│ cz/onadne ┆ Hykl"]    ┆ chce být  ┆ Eudoxie   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ s/v…      ┆           ┆ jak…      ┆ Yao …     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Splní dom ┆ Vozy s    ┆ … ┆ []        ┆ 0         ┆ 4         ┆ 2014-08- │
│ ww.idnes. ┆           ┆ inantní   ┆ velkou    ┆   ┆           ┆           ┆           ┆ 21       │
│ cz/sport/ ┆           ┆ mercedesy ┆ maximální ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ mot…      ┆           ┆ rol…      ┆ rychlo…   ┆   ┆           ┆           ┆           ┆          │
│ https://v ┆ ["Dušan   ┆ Náraz     ┆ Halenkov  ┆ … ┆ [1]       ┆ 1         ┆ 1         ┆ 2016-01- │
│ alassky.d ┆ Póč"]     ┆ auta do   ┆ – Ohromné ┆   ┆           ┆           ┆           ┆ 11       │
│ enik.cz/n ┆           ┆ vlaku se  ┆ štěstí    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ eho…      ┆           ┆ obešel …  ┆ stál…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Írán      ┆ Írán      ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2011-08- │
│ ww.novink ┆           ┆ přesouvá  ┆ začal     ┆   ┆           ┆           ┆           ┆ 22       │
│ y.cz/zahr ┆           ┆ centrifug ┆ stěhovat  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ani…      ┆           ┆ y na ob…  ┆ centrifug ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ y…        ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ []        ┆ Vládní    ┆ ODS, TOP  ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2012-04- │
│ pravy.akt ┆           ┆ krize     ┆ 09 a VV   ┆   ┆           ┆           ┆           ┆ 11       │
│ ualne.cz/ ┆           ┆ končí,    ┆ se v      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ dom…      ┆           ┆ rozhádaná ┆ úterý do… ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df03_train = pl.from_arrow(ds03["train"].data.table)
df03_train.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Twerkujíc ┆ Basketbal ┆ … ┆ []        ┆ 0         ┆ 7         ┆ 2019-04- │
│ ww.novink ┆           ┆ í babičky ┆ ový celek ┆   ┆           ┆           ┆           ┆ 07       │
│ y.cz/kokt ┆           ┆ se staly  ┆ Washingto ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ejl…      ┆           ┆ se…       ┆ n …       ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Světové   ┆ Několik   ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2018-01- │
│ ww.novink ┆           ┆ automobil ┆ tisíc     ┆   ┆           ┆           ┆           ┆ 24       │
│ y.cz/ekon ┆           ┆ ky nevydě ┆ lidí      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ omi…      ┆           ┆ láva…     ┆ hodlá     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ propu…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Opilý     ┆ Policisté ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2019-04- │
│ ww.novink ┆           ┆ zloděj    ┆ a hasiči  ┆   ┆           ┆           ┆           ┆ 03       │
│ y.cz/kokt ┆           ┆ uvízl v   ┆ museli ne ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ejl…      ┆           ┆ šachtě,   ┆ c…        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ s…        ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Karel   ┆ Nad       ┆ „V Sidi   ┆ … ┆ [1]       ┆ 1         ┆ 4         ┆ 2015-04- │
│ ww.novink ┆ Černý"]   ┆ knihou:   ┆ Moumen    ┆   ┆           ┆           ┆           ┆ 09       │
│ y.cz/kult ┆           ┆ Další     ┆ patřila   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ura…      ┆           ┆ zpráva o  ┆ smrt ke…  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ban…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Nabídky   ┆ V         ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2012-12- │
│ ww.novink ┆           ┆ operátorů ┆ nabídkách ┆   ┆           ┆           ┆           ┆ 12       │
│ y.cz/ekon ┆           ┆ chápe     ┆ mobilních ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ omi…      ┆           ┆ minimu…   ┆ operátor… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df03_validation = pl.from_arrow(ds03["validation"].data.table)
df03_validation.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://k ┆ ["Milan   ┆ Zeleň za  ┆ Výsadba   ┆ … ┆ [1]       ┆ 1         ┆ 2         ┆ 2020-06- │
│ olinsky.d ┆ Holakovsk ┆ miliony   ┆ zeleně na ┆   ┆           ┆           ┆           ┆ 30       │
│ enik.cz/z ┆ ý"]       ┆ má mazat  ┆ 651       ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ -re…      ┆           ┆ uhlí…     ┆ místech … ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Iva Kov ┆ Vězni     ┆ Ochranné  ┆ … ┆ [2]       ┆ 2         ┆ 2         ┆ 2020-04- │
│ ww.denik. ┆ ářová"]   ┆ pomáhají  ┆ látkové   ┆   ┆           ┆           ┆           ┆ 07       │
│ cz/region ┆           ┆ policistů ┆ roušky    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ y/v…      ┆           ┆ m i lé…   ┆ šije t…   ┆   ┆           ┆           ┆           ┆          │
│ https://f ┆ ["Roman   ┆ Stromský  ┆ Letošní   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2020-05- │
│ m.denik.c ┆ Brhel"]   ┆ bude na   ┆ dostihová ┆   ┆           ┆           ┆           ┆ 06       │
│ z/ostatni ┆           ┆ dostizích ┆ sezona    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ _re…      ┆           ┆ pop…      ┆ bude …    ┆   ┆           ┆           ┆           ┆          │
│ https://h ┆ ["Liba    ┆ Vánoční   ┆ Na první  ┆ … ┆ [2]       ┆ 2         ┆ 7         ┆ 2020-11- │
│ ranicky.d ┆ Mátlová"] ┆ strom v   ┆ adventní  ┆   ┆           ┆           ┆           ┆ 29       │
│ enik.cz/z ┆           ┆ Hranicích ┆ neděli se ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ pra…      ┆           ┆ se r…     ┆ ro…       ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Ivana   ┆ Fakulta v ┆ Pro       ┆ … ┆ [2]       ┆ 2         ┆ 4         ┆ 2020-07- │
│ ww.idnes. ┆ Lesková"] ┆ Ostravě   ┆ zájemce o ┆   ┆           ┆           ┆           ┆ 09       │
│ cz/ostrav ┆           ┆ nemůže    ┆ studium   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ a/z…      ┆           ┆ přijí…    ┆ medicíny… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df03_test = pl.from_arrow(ds03["test"].data.table)
df03_test.sample(5)

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://t ┆ ["Petr    ┆ Pytlačili ┆ Hlídka    ┆ … ┆ [1]       ┆ 1         ┆ 5         ┆ 2022-08- │
│ eplicky.d ┆ Málek"]   ┆ na        ┆ strážníků ┆   ┆           ┆           ┆           ┆ 05       │
│ enik.cz/z ┆           ┆ Vápence v ┆ v Krupce  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ loc…      ┆           ┆ Krupce,…  ┆ lapi…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Tomáš   ┆ Dosud     ┆ Kontakt s ┆ … ┆ [1]       ┆ 1         ┆ 7         ┆ 2021-05- │
│ ww.idnes. ┆ Šťástka"] ┆ bavili na ┆ diváky    ┆   ┆           ┆           ┆           ┆ 02       │
│ cz/kultur ┆           ┆ homeoffic ┆ udržovali ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ a/d…      ┆           ┆ u, ny…    ┆ her…      ┆   ┆           ┆           ┆           ┆          │
│ https://l ┆ []        ┆ Origináln ┆ Na velkou ┆ … ┆ []        ┆ 0         ┆ 5         ┆ 2022-05- │
│ iberecky. ┆           ┆ í rapper  ┆ dvoudenní ┆   ┆           ┆           ┆           ┆ 27       │
│ denik.cz/ ┆           ┆ Vojtaano  ┆ oslavu    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ cte…      ┆           ┆ pob…      ┆ stu…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Magdalé ┆ Děti od   ┆ Střelba v ┆ … ┆ [2]       ┆ 2         ┆ 3         ┆ 2022-05- │
│ ww.denik. ┆ na        ┆ krve,     ┆ malém     ┆   ┆           ┆           ┆           ┆ 25       │
│ cz/ze_sve ┆ Škapová"] ┆ chaos a   ┆ texaském  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ta/…      ┆           ┆ strach. … ┆ měste…    ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Dagmar  ┆ Kde seš   ┆ /VIDEO/   ┆ … ┆ [2]       ┆ 2         ┆ 4         ┆ 2022-01- │
│ nojemsky. ┆ Sedláčkov ┆ ty        ┆ Na parkov ┆   ┆           ┆           ┆           ┆ 06       │
│ denik.cz/ ┆ á"]       ┆ atrapo,   ┆ iště u    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zpr…      ┆           ┆ vítali se ┆ mostu …   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ z…        ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df04_train = pl.from_arrow(ds04["train"].data.table)
df04_train.sample(5)

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ Pak by si snad, či s mojí pomo… ┆ ["řekla", "řeklo", … "řekl"]    ┆ 2          │
│ Podklad nepochopitelně ____ op… ┆ ["zůstávala", "zůstávalo", … "… ┆ 4          │
│ Nějakých šedesát let ____ z vr… ┆ ["kouzlila", "kouzlilo", … "ko… ┆ 2          │
│ Když jsem ____ pozvání do Bart… ┆ ["dostala", "dostalo", … "dost… ┆ 0          │
│ A já jsem jenom ____ vždycky n… ┆ ["odpovídala", "odpovídalo", …… ┆ 4          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [12]:
df04_test = pl.from_arrow(ds04["test"].data.table)
df04_test.sample(5)

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ Cestou se ještě jejich jízdní … ┆ ["spojila", "spojilo", … "spoj… ┆ 3          │
│ Snažím se to kombinovat abych … ┆ ["procvičila", "procvičilo", …… ┆ 0          │
│ V roce 2004 ____ podhůří Vysok… ┆ ["postihla", "postihlo", … "po… ┆ 0          │
│ Karajda 2004 V roce 2004 se po… ┆ ["vrátila", "vrátilo", … "vrát… ┆ 4          │
│ Původní jméno Port Darwin ____… ┆ ["byla", "bylo", … "byl"]       ┆ 1          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [13]:
df05_train = pl.from_arrow(ds05["train"].data.table)
df05_train.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Ministers ┆ Ministers ┆ … ┆ 3         ┆ 2021-02-2 ┆ 2         ┆ 180      │
│ ww.irozhl ┆           ┆ tvo       ┆ tvo       ┆   ┆           ┆ 4         ┆           ┆          │
│ as.cz/zpr ┆           ┆ poslalo   ┆ školství  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ avy…      ┆           ┆ ředitelům ┆ poslalo … ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Veronik ┆ Jeden     ┆ Češi si   ┆ … ┆ 1         ┆ 2021-12-0 ┆ 7         ┆ 188      │
│ ww.idnes. ┆ a Bělohlá ┆ kapr o    ┆ důležitos ┆   ┆           ┆ 6         ┆           ┆          │
│ cz/ekonom ┆ vková"]   ┆ Vánocích  ┆ t ryb a   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ nestačí.… ┆ jejic…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milosla ┆ Německo   ┆ Jak       ┆ … ┆ 4         ┆ 2021-04-0 ┆ 3         ┆ 29       │
│ ww.idnes. ┆ v Novák"] ┆ se        ┆ ostudné.  ┆   ┆           ┆ 1         ┆           ┆          │
│ cz/fotbal ┆           ┆ ztrapnilo ┆ Jak       ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /re…      ┆           ┆ až na     ┆ trapné.   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ kos…      ┆ Jak h…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Vojáci    ┆ Bulharský ┆ … ┆ 4         ┆ 2021-06-0 ┆ 1         ┆ 11       │
│ ww.irozhl ┆           ┆ USA při   ┆ majitel   ┆   ┆           ┆ 3         ┆           ┆          │
│ as.cz/zpr ┆           ┆ cvičení v ┆ továrničk ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ avy…      ┆           ┆ Bulha…    ┆ y n…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Statisíce ┆ Víkendové ┆ … ┆ 4         ┆ 2021-08-1 ┆ 1         ┆ 126      │
│ ww.seznam ┆           ┆ lidí bez  ┆ devastují ┆   ┆           ┆ 9         ┆           ┆          │
│ zpravy.cz ┆           ┆ domova a  ┆ cí        ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ tr…       ┆ zemětřes… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df05_test = pl.from_arrow(ds05["test"].data.table)
df05_test.sample(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Ukrajina  ┆ Ukrajina  ┆ … ┆ 5         ┆ 2022-07-0 ┆ 7         ┆ 94       │
│ ww.idnes. ┆           ┆ začala    ┆ začala    ┆   ┆           ┆ 1         ┆           ┆          │
│ cz/ekonom ┆           ┆ vyvážet   ┆ vyvážet   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ elektř…   ┆ elektr…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Adam    ┆ Bla bla   ┆ Švédská   ┆ … ┆ 5         ┆ 2021-11-0 ┆ 1         ┆ 108      │
│ ww.seznam ┆ Ryšánek"] ┆ bla.      ┆ aktivistk ┆   ┆           ┆ 5         ┆           ┆          │
│ zpravy.cz ┆           ┆ Lídři nic ┆ a Greta   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ nedělaj…  ┆ Thunb…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milosla ┆ Žhavá     ┆ Jeden z   ┆ … ┆ 3         ┆ 2021-11-2 ┆ 3         ┆ 65       │
│ ww.idnes. ┆ v Novák"] ┆ odveta v  ┆ těch      ┆   ┆           ┆ 4         ┆           ┆          │
│ cz/fotbal ┆           ┆ Glasgow.  ┆ velkých a ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /po…      ┆           ┆ Spartě…   ┆ atrakti…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Na Kokoří ┆ V         ┆ … ┆ 4         ┆ 2021-08-1 ┆ 2         ┆ 119      │
│ ww.seznam ┆           ┆ nsku      ┆ letošním  ┆   ┆           ┆ 9         ┆           ┆          │
│ zpravy.cz ┆           ┆ začalo    ┆ srpnu a   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ natáčení  ┆ září      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆ režisé…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Natálie ┆ Místo afg ┆ V sobotu  ┆ … ┆ 7         ┆ 2021-08-2 ┆ 1         ┆ 60       │
│ ww.seznam ┆ Sousa"]   ┆ hánských  ┆ večer     ┆   ┆           ┆ 9         ┆           ┆          │
│ zpravy.cz ┆           ┆ uprchlíků ┆ vzlétlo z ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ př…       ┆ kábul…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df06 = pl.from_arrow(ds06["test"].data.table)
df06.sample(5)

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────┬─────────────┬─────────────┐
│ url          ┆ headline     ┆ brief        ┆ keywords     ┆ category ┆ content     ┆ category_un │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---      ┆ ---         ┆ clean       │
│ str          ┆ str          ┆ str          ┆ list[str]    ┆ i64      ┆ str         ┆ ---         │
│              ┆              ┆              ┆              ┆          ┆             ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════╪═════════════╪═════════════╡
│ https://www. ┆ S Janem      ┆ Rodina,      ┆ ["Pavel      ┆ 4        ┆ Poslední    ┆ Kultura     │
│ idnes.cz/kul ┆ Vodňanským   ┆ kolegové a   ┆ bém", "Jan   ┆          ┆ rozloučení  ┆             │
│ tura/h…      ┆ se naposled… ┆ přátelé se … ┆ hřebejk", …… ┆          ┆ s Janem Vo… ┆             │
│ https://maga ┆ Don Juan     ┆ Plameny      ┆ ["Opera",    ┆ 4        ┆ Plameny     ┆ Klasická    │
│ zin.aktualne ┆ jako fantasm ┆ žhnoucí      ┆ "Don juan",  ┆          ┆ představují ┆ hudba       │
│ .cz/ku…      ┆ agorie kr…   ┆ touhy,       ┆ … "Josif…    ┆          ┆ zcela jino… ┆             │
│              ┆              ┆ nedosti…     ┆              ┆          ┆             ┆             │
│ https://www. ┆ Home Credit  ┆ Skupina Home ┆ ["Čína",     ┆ 5        ┆ Home Credit ┆ Ekonomika   │
│ idnes.cz/eko ┆ snížil počet ┆ Credit       ┆ "Aljaška", … ┆          ┆ na svém     ┆             │
│ nomika…      ┆ zaměs…       ┆ musela po …  ┆ "Ks-jobd…    ┆          ┆ webu uvádí… ┆             │
│ https://svit ┆ Janek        ┆ /FOTO,       ┆ []           ┆ 4        ┆ „Je to      ┆ Kultura     │
│ avsky.denik. ┆ Ledecký      ┆ VIDEO/ Janek ┆              ┆          ┆ normální    ┆             │
│ cz/kul…      ┆ odstartoval  ┆ Ledecký za…  ┆              ┆          ┆ průběh      ┆             │
│              ┆ v Li…        ┆              ┆              ┆          ┆ nemoci,…    ┆             │
│ https://www. ┆ Nová         ┆ Protilátku,  ┆ []           ┆ 1        ┆ O objevu    ┆ Zahraniční  │
│ novinky.cz/z ┆ protilátka   ┆ která brání  ┆              ┆          ┆ informoval  ┆             │
│ ahrani…      ┆ zcela        ┆ replik…      ┆              ┆          ┆ tým v časo… ┆             │
│              ┆ blokuje …    ┆              ┆              ┆          ┆             ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────┴─────────────┴─────────────┘

### ***Creating a summary data file***

In [16]:
def build_unified_contexts(ds01, ds02, ds03, ds04, ds05, ds06):
    print("I am starting the unification of Czech text contexts using Polars...")
    
    # --- 1. News Corpus (Hynky v2 - 1.6M+ lines) ---
    # We glue the title, annotation and the entire body of the article into one massive block
    df_news = pl.from_arrow(ds03["train"].data.table).lazy().select([
        (pl.col("headline") + "\n" + pl.col("brief") + "\n" + pl.col("content")).alias("context"),
        pl.lit("news").alias("source")
    ])
    
    # --- 2. Legal / Alpaca dataset (czech-justice-summ-alpaca-long) ---
    # Here it makes sense to combine the instruction and the answer into one continuous text
    df_alpaca = pl.from_arrow(ds02["train"].data.table).lazy().select([
        (pl.col("instruction") + "\n" + pl.col("output")).alias("context"),
        pl.lit("alpaca_justice").alias("source")
    ])
    
    # --- 3. CERMAT Dataset (cermat_czech_mc) ---
    # Here we have the 'context' column, which we can enrich with a question
    df_cermat = pl.from_arrow(ds01["test"].data.table).lazy().select([
        (pl.col("context") + "\nOtázka: " + pl.col("query")).alias("context"),
        pl.lit("cermat").alias("source")
    ])

    # --- 4. Concatenation of all streams ---
    # Polars performs vertical joins extremely fast without unnecessary duplicate memory allocation
    unified_lazy = pl.concat([df_news, df_alpaca, df_cermat])
    
    # --- 5. Text extraction and cleaning + Calculation of logical predicates for JLNN ---
    final_df = unified_lazy.filter(
        pl.col("context").is_not_null() & (pl.col("context").str.len_chars() > 50)
    ).select([
        # Clean resulting text (context)
        pl.col("context"),
        pl.col("source"),
        
        # [PREDICT A]: Detection of masculine nouns in the text (Axiom of subject-predicate agreement)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["chlapci", "muži", "dělníci", "studenti", "hráči", "učitelé", "lidi", "psi"]
        ).cast(pl.Float32).alias("has_masc_animate"),
        
        # [PREDICATE C]: Detection of subordinating conjunctions introducing subordinate clauses (Axiom of Punctuation)
        pl.col("context").str.to_lowercase().str.contains_any(
            ["že", "protože", "aby", "který", "jelikož", "jakmile", "zatímco"]
        ).cast(pl.Float32).alias("has_subord_conjunction"),
        
        # Auxiliary check: Is there a comma present in the text? (Basis for evaluating the t-norm)
        pl.col("context").str.contains(",").cast(pl.Float32).alias("has_comma")
    ]).collect()
    
    print(f"Unification complete! Total number of entire contexts in dataset: {final_df.height:,}")
    return final_df

In [17]:
%%time
df_dataset = build_unified_contexts(ds01, ds02, ds03, ds04, ds05, ds06)
df_dataset.sample(5)

I am starting the unification of Czech text contexts using Polars...
Unification complete! Total number of entire contexts in dataset: 1,646,599
CPU times: user 1min 17s, sys: 7.56 s, total: 1min 24s
Wall time: 1min 20s

shape: (5, 5)
┌─────────────────────────────────┬────────┬──────────────────┬────────────────────────┬───────────┐
│ context                         ┆ source ┆ has_masc_animate ┆ has_subord_conjunction ┆ has_comma │
│ ---                             ┆ ---    ┆ ---              ┆ ---                    ┆ ---       │
│ str                             ┆ str    ┆ f32              ┆ f32                    ┆ f32       │
╞═════════════════════════════════╪════════╪══════════════════╪════════════════════════╪═══════════╡
│ Google pomalu privatizuje Andr… ┆ news   ┆ 1.0              ┆ 1.0                    ┆ 1.0       │
│ Chávez se nechal kvůli chemote… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
│ Kradená auta odváželi do kovoš… ┆ news   ┆ 1.0              ┆ 1.0                    ┆ 1.0       │
│ Hráč od pánaboha i provokatér.… ┆ news   ┆ 1.0              ┆ 1.0                    ┆ 1.0       │
│ Kontroverzní sKarty definitivn… ┆ news   ┆ 0.0              ┆ 1.0                    ┆ 1.0       │
└─────────────────────────────────┴────────┴──────────────────┴────────────────────────┴───────────┘

### ***Preparing the RAW dataset (Pure sentence extraction in Polars)***

In [18]:
def create_raw_sentence_dataset(unified_df):
    print("I extract clean sentence segments and classify their punctuation...")
    
    # This regex finds any characters that end with either a period, question mark, exclamation mark, comma,
    # or at the end of the entire text. This will keep the sign right at the end of the segment!
    regex_segment_with_punc = r"[^.\?!,]+[\.\?!,]?"

    raw_segments = (
        unified_df
        # 1. We extract all the matching sentence segments as a Word List
        .select(
            pl.col("context").str.extract_all(regex_segment_with_punc)
        )
        # 2. Expand the sheet into separate rows
        .explode("context")
        .rename({"context": "segment"})
        
        # 3. We clean up spaces at the beginning and end (the stuck punctuation will remain)
        .with_columns(pl.col("segment").str.strip_chars())
        
        # 4. FILTERING: We remove empty or too short things
        .filter(
            (pl.col("segment").str.len_chars() > 5) & 
            (pl.col("segment").str.len_chars() < 200) &
            pl.col("segment").str.contains(r"[a-zA-Zá-žÁ-Ž]")
        )
        
        # 5. CLASSIFICATION OF TERMINAL TYPE
        .with_columns([
            pl.when(pl.col("segment").str.ends_with("?")).then(pl.lit("otazník"))
            .when(pl.col("segment").str.ends_with("!")).then(pl.lit("vykřičník"))
            .when(pl.col("segment").str.ends_with(".")).then(pl.lit("tečka"))
            .when(pl.col("segment").str.ends_with(",")).then(pl.lit("čárka"))
            .otherwise(pl.lit("žádná"))
            .alias("punctuation_type")
        ])
        
        # 6. Random sample for our Ollama
        .sample(n=10000, with_replacement=False, seed=42)
    )
    
    print(f"Prepared {raw_segments.height} sentence segments for Ollama.")
    return raw_segments

In [19]:
%%time
raw_sentence_df = create_raw_sentence_dataset(df_dataset)
raw_sentence_df.head(5)

I extract clean sentence segments and classify their punctuation...
Prepared 10000 sentence segments for Ollama.
CPU times: user 1min 44s, sys: 6.85 s, total: 1min 51s
Wall time: 1min 50s

shape: (5, 2)
┌─────────────────────────────────┬──────────────────┐
│ segment                         ┆ punctuation_type │
│ ---                             ┆ ---              │
│ str                             ┆ str              │
╞═════════════════════════════════╪══════════════════╡
│ Pokud se to stává opakovaně,    ┆ čárka            │
│ Připomeňte si letošní změny: R… ┆ čárka            │
│ Ani to však značku patřící pod… ┆ tečka            │
│ dopadly do moře                 ┆ čárka            │
│ Severní Korea …                 ┆                  │
│ „Někdy stačí i jen velká popel… ┆ čárka            │
└─────────────────────────────────┴──────────────────┘

### ***Export dataset***

In [20]:
def export_polars_to_pyarrow_dataset(polars_df, output_dir="processed_dataset"):
    print("Converting Polars DataFrame to PyArrow Table...")
    
    # We define a dictionary for translating Czech values ​​into English folder names
    translation_dict = {
        "otazník": "question_mark",
        "vykřičník": "exclamation_mark",
        "tečka": "period",
        "čárka": "comma",
        "žádná": "none"
    }
    
    # Temporarily add a column for folders in Polars and immediately convert to Arrow
    arrow_table = (
        polars_df
        .with_columns(
            pl.col("punctuation_type").replace(translation_dict).alias("folder_name")
        )
        .to_arrow()
    )
    
    print(f"PyArrow table ready. Number of rows: {arrow_table.num_rows:,}")
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Saving PyArrow Dataset to folder '{output_dir}' with English names...")
    
    # Writing to disk - partition will be done according to "folder_name" (English)
    ds.write_dataset(
        data=arrow_table,
        base_dir=output_dir,
        format="parquet",
        partitioning=["folder_name"],
        use_threads=True,
        existing_data_behavior="overwrite_or_ignore"
    )
    
    print("Export completed successfully!")

In [21]:
%%time
export_polars_to_pyarrow_dataset(raw_sentence_df, output_dir="raw_segments_dataset")

Converting Polars DataFrame to PyArrow Table...
PyArrow table ready. Number of rows: 10,000
Saving PyArrow Dataset to folder 'raw_segments_dataset' with English names...
Export completed successfully!
CPU times: user 29.1 ms, sys: 9.17 ms, total: 38.3 ms
Wall time: 60.8 ms