--------------------------------------------------
# **Create Czech text dataset for training**
-------------------------------------------------

In [1]:
!apt install git-lfs

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git-lfs is already the newest version (3.0.2-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.

## ***Imports***

In [2]:
import os, sys
import zipfile
import subprocess
import io
import shutil
import json
import polars as pl
import numpy as np
import pyarrow as pa
import pickle

import pyarrow.parquet as pq

from huggingface_hub import (
    get_full_repo_name,
    login,
    upload_folder,
    hf_hub_download,
    HfApi
)


from datasets import load_dataset
from kaggle_secrets import UserSecretsClient
from tqdm import tqdm

## ***Hugging Face Login***

In [3]:
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")
user_email = user_secrets.get_secret("user_email")
user_name = user_secrets.get_secret("user_name")

login(token=hf_token)

### ***Data files***

1. ***CZLC/cermat_czech_mc***
   
   The **Cermat Czech MultiChoice** dataset was collected from assignments official CERMAT website. The dataset was collected from three tiers of assignments: 6 year, 9 year primary school test and final high school tests (so-called maturita). The assignments were semi-manually extracted from official PDFs available at [CERMAT's website](https://maturita.cermat.cz/menu/testy-a-zadani-z-predchozich-obdobi/matematika/testy-a-zadani-matematika).

    **Collection Date Range:** years 2016-2023

    ***Licensing and Credits***

    The majority of collection work was done by our student co-worker Jan Kapsa. Members of CZLC do not own the test assignments, neither are responsible for their contents.

    **Source:** https://huggingface.co/datasets/CZLC/cermat_czech_mc
 
2. ***hynky/czech-justice-summ-alpaca-long***

    **Source:** https://huggingface.co/datasets/hynky/czech-justice-summ-alpaca-long

3. ***hynky/czech_news_dataset_v2***

    Dataset containing the news articles from major online news outlets collected from 2000-2022.
    Follow-up paper https://arxiv.org/abs/2307.10666 (v1 of the dataset)

    Changes from v1:
        - Better contribution of novinky.cz in later stages
        - More articles, as a mistake in filtering was fixed.

   Collection was done using CmonCrawl.

   The dataset should be used for Research only purposes as I don't have rights for articles itself.

   **Source:** https://huggingface.co/datasets/hynky/czech_news_dataset_v2

4. ***davidadamczyk/czechbench_agree***

   This is an adapted and filtered test subset from the original Czech grammar agreement dataset

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_agree

6. ***davidadamczyk/czechbench_czech_news***

   This is a simplified and subsampled test subset from the original [czech_news_dataset_v2](https://huggingface.co/datasets/hynky/czech_news_dataset_v2).

   **Source:** https://huggingface.co/datasets/davidadamczyk/czechbench_czech_news

8. ***CIIRC-NLP/czech_news_simple-cs***

   **Source:** https://huggingface.co/datasets/CIIRC-NLP/czech_news_simple-cs

   This is a simplified and subsampled test subset from the original czech_news_dataset_v2.

   Only 5 basic news categories are considered:

   - Foreign
   - Local
   - Sports
   - Economy

   The test set includes 200 examples per category, 1000 examples in total. Apart from the category label, each example also contains the article's headline, brief summary, full textual content, optional keywords, original category specification, and URL.

   This dataset was created for use within the [Czech-Bench](https://gitlab.com/jirkoada/czech-bench) evaluation framework.

In [4]:
ds01 = load_dataset("CZLC/cermat_czech_mc")
ds02 = load_dataset("hynky/czech-justice-summ-alpaca-long")
ds03 = load_dataset("hynky/czech_news_dataset_v2")
ds04 = load_dataset("davidadamczyk/czechbench_agree")
ds05 = load_dataset("davidadamczyk/czechbench_czech_news")
ds06 = load_dataset("CIIRC-NLP/czech_news_simple-cs", "default")

README.md: 0.00B [00:00, ?B/s]

test.jsonl: 0.00B [00:00, ?B/s]

Generating test split:   0%|          | 0/649 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/503 [00:00<?, ?B/s]

data/train-00000-of-00001-93f855e5cee8b5(…):   0%|          | 0.00/12.6M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4560 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00011-c758fbca39d29e(…):   0%|          | 0.00/285M [00:00<?, ?B/s]

data/train-00001-of-00011-04ed5181478f78(…):   0%|          | 0.00/283M [00:00<?, ?B/s]

data/train-00002-of-00011-7bab2e4f395098(…):   0%|          | 0.00/290M [00:00<?, ?B/s]

data/train-00003-of-00011-4f3be47507ad60(…):   0%|          | 0.00/300M [00:00<?, ?B/s]

data/train-00004-of-00011-eba4d38f0a5bd6(…):   0%|          | 0.00/317M [00:00<?, ?B/s]

data/train-00005-of-00011-1532bd3e35e037(…):   0%|          | 0.00/327M [00:00<?, ?B/s]

data/train-00006-of-00011-a90e9830da712d(…):   0%|          | 0.00/337M [00:00<?, ?B/s]

data/train-00007-of-00011-da6a604299b8e7(…):   0%|          | 0.00/328M [00:00<?, ?B/s]

data/train-00008-of-00011-2bd7fa9bb613ff(…):   0%|          | 0.00/312M [00:00<?, ?B/s]

data/train-00009-of-00011-2ccab243ff4f0d(…):   0%|          | 0.00/314M [00:00<?, ?B/s]

data/train-00010-of-00011-271947731579c0(…):   0%|          | 0.00/326M [00:00<?, ?B/s]

data/validation-00000-of-00002-d13428425(…):   0%|          | 0.00/173M [00:00<?, ?B/s]

data/validation-00001-of-00002-b8b386fb0(…):   0%|          | 0.00/175M [00:00<?, ?B/s]

data/test-00000-of-00002-9f5fef591354e92(…):   0%|          | 0.00/178M [00:00<?, ?B/s]

data/test-00001-of-00002-be0d3a48e095e91(…):   0%|          | 0.00/188M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1641471 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/144836 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/144837 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/4.27k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/607 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/92.9k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/2.64M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/980 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/test-00000-of-00001-8fd5c2a953da2a2(…):   0%|          | 0.00/2.67M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [5]:
print(type(ds01),'\n',ds01)
print(type(ds02),'\n',ds02)
print(type(ds03),'\n',ds03)
print(type(ds04),'\n',ds04)
print(type(ds05),'\n',ds05)
print(type(ds06),'\n',ds06)

<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['type', 'query', 'choices', 'gold', 'context', 'subject', 'difficulty', 'source'],
        num_rows: 649
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['output', 'instruction'],
        num_rows: 4560
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 1641471
    })
    validation: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144836
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date'],
        num_rows: 144837
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 20
    })
    test: Dataset({
        features: ['sentence', 'choices', 'answer_idx'],
        num_rows: 607
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    train: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 20
    })
    test: Dataset({
        features: ['url', 'authors', 'headline', 'brief', 'keywords', 'category', 'content', 'comments_num', 'server', 'category_unclean', 'authors_gender', 'authors_cum_gender', 'day_of_week', 'date', '__index_level_0__', '__index_level_1__'],
        num_rows: 980
    })
})
<class 'datasets.dataset_dict.DatasetDict'>
 DatasetDict({
    test: Dataset({
        features: ['url', 'headline', 'brief', 'keywords', 'category', 'content', 'category_unclean'],
        num_rows: 1000
    })
})

In [6]:
df01 = pl.from_arrow(ds01["test"].data.table)
df01

shape: (649, 8)
┌──────┬──────────────┬─────────────┬──────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ type ┆ query        ┆ choices     ┆ gold ┆ context     ┆ subject     ┆ difficulty  ┆ source      │
│ ---  ┆ ---          ┆ ---         ┆ ---  ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str  ┆ str          ┆ list[str]   ┆ i64  ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════╪══════════════╪═════════════╪══════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ MC   ┆ Které z násl ┆ ["A. Slovo  ┆ 1    ┆ Zprvu       ┆ český jazyk ┆ maturitní   ┆ jaro 2021   │
│      ┆ edujících    ┆ patřit je v ┆      ┆ prorežimní  ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ textu u…    ┆      ┆ spisovatel, ┆ literatura  ┆             ┆             │
│      ┆              ┆             ┆      ┆ n…          ┆             ┆             ┆             │
│ MC   ┆ Ve kterém z  ┆ ["A. za     ┆ 1    ┆ Zprvu       ┆ český jazyk ┆ maturitní   ┆ jaro 2021   │
│      ┆ následujícíc ┆ kritiku     ┆      ┆ prorežimní  ┆ a           ┆ zkouška     ┆             │
│      ┆ h úsek…      ┆ režimu si   ┆      ┆ spisovatel, ┆ literatura  ┆             ┆             │
│      ┆              ┆ nadě…       ┆      ┆ n…          ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A.        ┆ 3    ┆ Zprvu       ┆ český jazyk ┆ maturitní   ┆ jaro 2021   │
│      ┆ edujících    ┆ Zájmeno mu  ┆      ┆ prorežimní  ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ zastupuje   ┆      ┆ spisovatel, ┆ literatura  ┆             ┆             │
│      ┆              ┆ velv…       ┆      ┆ n…          ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. Ve     ┆ 3    ┆ Hloučky     ┆ český jazyk ┆ maturitní   ┆ jaro 2021   │
│      ┆ edujících    ┆ výchozím    ┆      ┆ nedočkavých ┆ a           ┆ zkouška     ┆             │
│      ┆ tvrzení …    ┆ textu je    ┆      ┆ lidí postá… ┆ literatura  ┆             ┆             │
│      ┆              ┆ chyb…       ┆      ┆             ┆             ┆             ┆             │
│ MC   ┆ Na každé ze  ┆ ["A.        ┆ 1    ┆ <bold>(1)</ ┆ český jazyk ┆ maturitní   ┆ jaro 2021   │
│      ┆ dvou         ┆ oponentů –  ┆      ┆ bold> Když  ┆ a           ┆ zkouška     ┆             │
│      ┆ vynechaných  ┆ imponují",  ┆      ┆ poslouch…   ┆ literatura  ┆             ┆             │
│      ┆ m…           ┆ "B.…        ┆      ┆             ┆             ┆             ┆             │
│ …    ┆ …            ┆ …           ┆ …    ┆ …           ┆ …           ┆ …           ┆ …           │
│ MC   ┆ Které z násl ┆ ["A. Slovo  ┆ 2    ┆ (1) Díky    ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ edujících    ┆ bohatý je v ┆      ┆ nálezům     ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ tvrzení …    ┆ textu u…    ┆      ┆ nástrojů,   ┆ literatura  ┆             ┆             │
│      ┆              ┆             ┆      ┆ zbr…        ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A.        ┆ 3    ┆ (1) Díky    ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ edujících    ┆ Výchozí     ┆      ┆ nálezům     ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ tvrzení …    ┆ text popírá ┆      ┆ nástrojů,   ┆ literatura  ┆             ┆             │
│      ┆              ┆ infor…      ┆      ┆ zbr…        ┆             ┆             ┆             │
│ MC   ┆ Která z násl ┆ ["A. jednod ┆ 2    ┆ (1) Díky    ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ edujících    ┆ uchých      ┆      ┆ nálezům     ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ možností…    ┆ textů,      ┆      ┆ nástrojů,   ┆ literatura  ┆             ┆             │
│      ┆              ┆ včetn…      ┆      ┆ zbr…        ┆             ┆             ┆             │
│ MC   ┆ Na každé ze  ┆ ["A. vysvět ┆ 3    ┆ (1) Černá   ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ dvou         ┆ leních –    ┆      ┆ skříňka,    ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ vynechaných  ┆ dvěmi", "B… ┆      ┆ jeden z     ┆ literatura  ┆             ┆             │
│      ┆ m…           ┆             ┆      ┆ klí…        ┆             ┆             ┆             │
│ MC   ┆ Které z násl ┆ ["A. V      ┆ 0    ┆ (1) Černá   ┆ český jazyk ┆ šestiletá   ┆ 2. řádný    │
│      ┆ edujících    ┆ textu jsou  ┆      ┆ skříňka,    ┆ a           ┆ gymnázia    ┆ termín 2021 │
│      ┆ tvrzení …    ┆ podtrženy   ┆      ┆ jeden z     ┆ literatura  ┆             ┆             │
│      ┆              ┆ dv…         ┆      ┆ klí…        ┆             ┆             ┆             │
└──────┴──────────────┴─────────────┴──────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
df02 = pl.from_arrow(ds03["train"].data.table)
df02

shape: (1_641_471, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Svět      ┆ Ohňostroj ┆ … ┆ []        ┆ 0         ┆ 6         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ bouřlivě  ┆ i, veseli ┆   ┆           ┆           ┆           ┆ 01       │
│ cz/zpravy ┆           ┆ oslavoval ┆ cemi a s  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /za…      ┆           ┆ přícho…   ┆ jás…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Program   ┆ Značně    ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ fotbalist ┆ neoblíben ┆   ┆           ┆           ┆           ┆ 03       │
│ cz/fotbal ┆           ┆ ů: běžky  ┆ é         ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ a dř…     ┆ obodobí,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tvr…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Fotbalist ┆ Do 19.    ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ é začali  ┆ února,    ┆   ┆           ┆           ┆           ┆ 03       │
│ cz/fotbal ┆           ┆ přípravu  ┆ kdy začne ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ na …      ┆ jarní …   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Tlustý:   ┆ ODS bude  ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ ODS bude  ┆ na        ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/zpravy ┆           ┆ žádat     ┆ pátečním  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /do…      ┆           ┆ rekonst…  ┆ jednání   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ s…        ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Na ligu   ┆ V         ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ se        ┆ nesmírně  ┆   ┆           ┆           ┆           ┆ 05       │
│ cz/fotbal ┆           ┆ chystají  ┆ vyrovnané ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ nedávní   ┆ tabulce   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ma…       ┆ f…        ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://a ┆ ["Radek   ┆ Slovenský ┆ Britsko-i ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Pecák"]   ┆ Land      ┆ ndická    ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆           ┆ Rover     ┆ automobil ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ Defender  ┆ ka La…    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Daniel  ┆ Rakouská  ┆ Většina   ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Fuglevič" ┆ firma     ┆ elektromo ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆ ]         ┆ nabízí    ┆ bilů na   ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ ikonické… ┆ trhu …    ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Radek   ┆ Poslední  ┆ Ještě     ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Pecák"]   ┆ "německý" ┆ letos na  ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆           ┆ Passat    ┆ jaře      ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ odta…     ┆ sjede z   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ vý…       ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Jan Mar ┆ Bentley   ┆ Tohle je  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ kovič"]   ┆ slaví     ┆ zřejmě    ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/ma ┆           ┆ století   ┆ nejdražší ┆   ┆           ┆           ┆           ┆          │
│ gaz…      ┆           ┆ luxusní … ┆ auto…     ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Dominik ┆ První     ┆ Zeptejte  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Valášek"] ┆ dojmy:    ┆ se libovo ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/te ┆           ┆ Subaru    ┆ lného     ┆   ┆           ┆           ┆           ┆          │
│ sty…      ┆           ┆ Impreza   ┆ člověk…   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ je…       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df03_train = pl.from_arrow(ds03["train"].data.table)
df03_train

shape: (1_641_471, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Svět      ┆ Ohňostroj ┆ … ┆ []        ┆ 0         ┆ 6         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ bouřlivě  ┆ i, veseli ┆   ┆           ┆           ┆           ┆ 01       │
│ cz/zpravy ┆           ┆ oslavoval ┆ cemi a s  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /za…      ┆           ┆ přícho…   ┆ jás…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Program   ┆ Značně    ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ fotbalist ┆ neoblíben ┆   ┆           ┆           ┆           ┆ 03       │
│ cz/fotbal ┆           ┆ ů: běžky  ┆ é         ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ a dř…     ┆ obodobí,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ tvr…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Fotbalist ┆ Do 19.    ┆ … ┆ []        ┆ 0         ┆ 1         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ é začali  ┆ února,    ┆   ┆           ┆           ┆           ┆ 03       │
│ cz/fotbal ┆           ┆ přípravu  ┆ kdy začne ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ na …      ┆ jarní …   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Tlustý:   ┆ ODS bude  ┆ … ┆ []        ┆ 0         ┆ 2         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ ODS bude  ┆ na        ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/zpravy ┆           ┆ žádat     ┆ pátečním  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /do…      ┆           ┆ rekonst…  ┆ jednání   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ s…        ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Na ligu   ┆ V         ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2000-01- │
│ ww.idnes. ┆           ┆ se        ┆ nesmírně  ┆   ┆           ┆           ┆           ┆ 05       │
│ cz/fotbal ┆           ┆ chystají  ┆ vyrovnané ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /pr…      ┆           ┆ nedávní   ┆ tabulce   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ma…       ┆ f…        ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://a ┆ ["Radek   ┆ Slovenský ┆ Britsko-i ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Pecák"]   ┆ Land      ┆ ndická    ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆           ┆ Rover     ┆ automobil ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ Defender  ┆ ka La…    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Daniel  ┆ Rakouská  ┆ Většina   ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Fuglevič" ┆ firma     ┆ elektromo ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆ ]         ┆ nabízí    ┆ bilů na   ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ ikonické… ┆ trhu …    ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Radek   ┆ Poslední  ┆ Ještě     ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Pecák"]   ┆ "německý" ┆ letos na  ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆           ┆ Passat    ┆ jaře      ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ odta…     ┆ sjede z   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ vý…       ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Jan Mar ┆ Bentley   ┆ Tohle je  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ kovič"]   ┆ slaví     ┆ zřejmě    ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/ma ┆           ┆ století   ┆ nejdražší ┆   ┆           ┆           ┆           ┆          │
│ gaz…      ┆           ┆ luxusní … ┆ auto…     ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Dominik ┆ První     ┆ Zeptejte  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Valášek"] ┆ dojmy:    ┆ se libovo ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/te ┆           ┆ Subaru    ┆ lného     ┆   ┆           ┆           ┆           ┆          │
│ sty…      ┆           ┆ Impreza   ┆ člověk…   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ je…       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df03_validation = pl.from_arrow(ds03["validation"].data.table)
df03_validation

shape: (144_836, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ ["Petr    ┆ Házenkáře ┆ Do roka a ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2020-03- │
│ ww.idnes. ┆ Bílek"]   ┆ Lovosic   ┆ do dne    ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/sport/ ┆           ┆ má do     ┆ skončil u ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ haz…      ┆           ┆ play o…   ┆ ház…      ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Francouzi ┆ Ve franco ┆ … ┆ []        ┆ 0         ┆ 3         ┆ 2020-03- │
│ ww.idnes. ┆           ┆ skupují   ┆ uzských   ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/kultur ┆           ┆ Mor od    ┆ knihkupec ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ a/l…      ┆           ┆ Camus…    ┆ tvíc…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jakub   ┆ Námraza   ┆ Námraza   ┆ … ┆ [1]       ┆ 1         ┆ 3         ┆ 2020-03- │
│ ww.idnes. ┆ Augusta"] ┆ zkompliko ┆ na        ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/praha/ ┆           ┆ vala      ┆ troleji   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ zpr…      ┆           ┆ ranní do… ┆ zkompliko ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ va…       ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Mirka   ┆ Zemřel    ┆ Populariz ┆ … ┆ [2]       ┆ 2         ┆ 3         ┆ 2020-03- │
│ ww.idnes. ┆ Spáčilová ┆ recitátor ┆ átor      ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/kultur ┆ "]        ┆ Miroslav  ┆ poezie    ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ a/f…      ┆           ┆ Ková…     ┆ Miroslav  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Markéta ┆ Jarní     ┆ Líčení je ┆ … ┆ [2]       ┆ 2         ┆ 3         ┆ 2020-03- │
│ ww.idnes. ┆ Škaldová" ┆ trendy v  ┆ pro       ┆   ┆           ┆           ┆           ┆ 04       │
│ cz/onadne ┆ ]         ┆ líčení,   ┆ většinu   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ s/m…      ┆           ┆ které s…  ┆ žen témě… ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://a ┆ ["Dominik ┆ Vybíráme  ┆ Dnes se v ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Valášek"] ┆ z         ┆ rámci     ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/oj ┆           ┆ inzerce:  ┆ našich    ┆   ┆           ┆           ┆           ┆          │
│ eta…      ┆           ┆ Auta      ┆ inzertn…  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ znače…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ http://ww ┆ []        ┆ MUDr. Ján ┆ Plastické ┆ … ┆ []        ┆ 0         ┆ 0         ┆ null     │
│ w.aktualn ┆           ┆ Pilka z   ┆ operace u ┆   ┆           ┆           ┆           ┆          │
│ e.cz/mudr ┆           ┆ Aesthevit ┆ mužů už   ┆   ┆           ┆           ┆           ┆          │
│ -ja…      ┆           ┆ a: …      ┆ dá…       ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Jiří    ┆ KIA       ┆ Podoby    ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Švamberk" ┆ uvolnila  ┆ reálného  ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆ ]         ┆ dvě skici ┆ vozu      ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ nového …  ┆ bychom    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ se…       ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Jiří    ┆ Automatic ┆ Jen malý  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Špreňar"] ┆ ká převod ┆ kousek od ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/zi ┆           ┆ ovka      ┆ nedobrovo ┆   ┆           ┆           ┆           ┆          │
│ vot…      ┆           ┆ pozlobi…  ┆ ln…       ┆   ┆           ┆           ┆           ┆          │
│ http://zp ┆ []        ┆ Paroubek  ┆ Šéf ČSSD  ┆ … ┆ []        ┆ 0         ┆ 0         ┆ null     │
│ ravy.idne ┆           ┆ nevylouči ┆ Jiří      ┆   ┆           ┆           ┆           ┆          │
│ s.cz/paro ┆           ┆ l menšino ┆ Paroubek  ┆   ┆           ┆           ┆           ┆          │
│ ube…      ┆           ┆ vou…      ┆ připust…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df03_test = pl.from_arrow(ds03["test"].data.table)
df03_test

shape: (144_837, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ authors_g ┆ authors_c ┆ day_of_we ┆ date     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ender     ┆ um_gender ┆ ek        ┆ ---      │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆ list[i64] ┆ i64       ┆ i64       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ ["Tomáš   ┆ Co v      ┆ Koronavir ┆ … ┆ [1]       ┆ 1         ┆ 2         ┆ 2021-02- │
│ ww.seznam ┆ Svoboda"] ┆ kampani   ┆ us        ┆   ┆           ┆           ┆           ┆ 16       │
│ zpravy.cz ┆           ┆ vystřídá  ┆ obrátil   ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /cl…      ┆           ┆ koblihy?… ┆ zájem     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ veře…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Štěpán  ┆ Bojím se, ┆ Digitální ┆ … ┆ [1]       ┆ 1         ┆ 2         ┆ 2021-02- │
│ ww.novink ┆ Kučera"]  ┆ že budu   ┆ René      ┆   ┆           ┆           ┆           ┆ 16       │
│ y.cz/kult ┆           ┆ jen       ┆ Descartes ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ura…      ┆           ┆ stroj. R… ┆ se zr…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jarosla ┆ ‚Aby      ┆ V Česku   ┆ … ┆ [1]       ┆ 1         ┆ 2         ┆ 2021-02- │
│ ww.irozhl ┆ v Hroch"] ┆ nemuseli  ┆ je už     ┆   ┆           ┆           ┆           ┆ 16       │
│ as.cz/zpr ┆           ┆ tlouct    ┆ přes      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ avy…      ┆           ┆ data      ┆ týden     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ dvak…     ┆ vakcí…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jarosla ┆ Nehoda    ┆ Hustě     ┆ … ┆ [1]       ┆ 1         ┆ 2         ┆ 2021-02- │
│ ww.denik. ┆ v         ┆ vlaků v   ┆ sněžilo.  ┆   ┆           ┆           ┆           ┆ 16       │
│ cz/ze_sve ┆ Krupka"]  ┆ Marylandu ┆ Byl únor  ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ ta/…      ┆           ┆ : sráž…   ┆ a po p…   ┆   ┆           ┆           ┆           ┆          │
│ https://m ┆ ["Magdale ┆ Co viděl  ┆ "V Nové   ┆ … ┆ [2]       ┆ 2         ┆ 2         ┆ 2021-02- │
│ agazin.ak ┆ na Čechlo ┆ inspektor ┆ pinakotéc ┆   ┆           ┆           ┆           ┆ 16       │
│ tualne.cz ┆ vská"]    ┆ pražské   ┆ e se      ┆   ┆           ┆           ┆           ┆ 00:00:00 │
│ /ku…      ┆           ┆ obr…      ┆ vůbec ne… ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://a ┆ ["Jiří    ┆ Hyundai   ┆ Novinka   ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Švamberk" ┆ představu ┆ se sporto ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/no ┆ ]         ┆ je své    ┆ vním      ┆   ┆           ┆           ┆           ┆          │
│ va-…      ┆           ┆ první …   ┆ stupněm … ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Daniel  ┆ Tohle     ┆ Koncept   ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Fuglevič" ┆ Bugatti   ┆ Bugatti   ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/ma ┆ ]         ┆ je jediné ┆ Vision    ┆   ┆           ┆           ┆           ┆          │
│ gaz…      ┆           ┆ na svě…   ┆ GT, kte…  ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Radek   ┆ Test      ┆ Testovaný ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Pecák"]   ┆ účinnosti ┆ exemplář  ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/zi ┆           ┆ klimatiza ┆ Renaultu  ┆   ┆           ┆           ┆           ┆          │
│ vot…      ┆           ┆ ce: Za…   ┆ Mé…       ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Daniel  ┆ Šílenost! ┆ Ano, zní  ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ Fuglevič" ┆ Kung-fu   ┆ to        ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/ma ┆ ]         ┆ mistr     ┆ opravdu   ┆   ┆           ┆           ┆           ┆          │
│ gaz…      ┆           ┆ svými …   ┆ šíleně. O ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ https://a ┆ ["Jan Mar ┆ S vzácným ┆ Vozu se   ┆ … ┆ [1]       ┆ 1         ┆ 0         ┆ null     │
│ utomix.de ┆ kovič"]   ┆ Porsche   ┆ vyrobilo  ┆   ┆           ┆           ┆           ┆          │
│ nik.cz/ma ┆           ┆ 911 do    ┆ jen něco  ┆   ┆           ┆           ┆           ┆          │
│ gaz…      ┆           ┆ kempu…    ┆ málo…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df04_train = pl.from_arrow(ds04["train"].data.table)
df04_train

shape: (20, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ ____ se na postupu a oficiální… ┆ ["Domluvila", "Domluvilo", … "… ┆ 2          │
│ Pondělí ____ očekávání meteoro… ┆ ["splnila", "splnilo", … "spln… ┆ 1          │
│ Strašně se mu ____, jak na ní … ┆ ["líbila", "líbilo", … "líbil"… ┆ 1          │
│ Nějakých šedesát let ____ z vr… ┆ ["kouzlila", "kouzlilo", … "ko… ┆ 2          │
│ ____ jste se vy s nějakým poku… ┆ ["Setkala", "Setkalo", … "Setk… ┆ 4          │
│ …                               ┆ …                               ┆ …          │
│ Na doporučení jsme vlastně ___… ┆ ["získala", "získalo", … "získ… ┆ 2          │
│ Okolnosti rozchodu (to, zda je… ┆ ["měla", "mělo", … "měl"]       ┆ 3          │
│ A spíš nedosáhl útěchy, až krv… ┆ ["uvrhnula", "uvrhnulo", … "uv… ┆ 4          │
│ ____ a nestačila se divit pros… ┆ ["Vstoupila", "Vstoupilo", … "… ┆ 0          │
│ Pak by si snad, či s mojí pomo… ┆ ["řekla", "řeklo", … "řekl"]    ┆ 2          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [12]:
df04_test = pl.from_arrow(ds04["test"].data.table)
df04_test

shape: (607, 3)
┌─────────────────────────────────┬─────────────────────────────────┬────────────┐
│ sentence                        ┆ choices                         ┆ answer_idx │
│ ---                             ┆ ---                             ┆ ---        │
│ str                             ┆ list[str]                       ┆ i64        │
╞═════════════════════════════════╪═════════════════════════════════╪════════════╡
│ Souhlasím, já ____ + - to samé… ┆ ["napsala", "napsalo", … "naps… ┆ 4          │
│ ____ jako leklá ryba se dvěma … ┆ ["Vypadala", "Vypadalo", … "Vy… ┆ 4          │
│ Podle ní by podnikatel ____ na… ┆ ["měla", "mělo", … "měl"]       ┆ 4          │
│ Ikonostas pochází s první polo… ┆ ["dochovala", "dochovalo", … "… ┆ 3          │
│ Dobře by ____ snad jen balerín… ┆ ["vypadala", "vypadalo", … "vy… ┆ 3          │
│ …                               ┆ …                               ┆ …          │
│ To pro mě ____ největší zážite… ┆ ["byla", "bylo", … "byl"]       ┆ 4          │
│ ____ jsem do nich Cimrmana, Ma… ┆ ["Tlačila", "Tlačilo", … "Tlač… ┆ 4          │
│ Vesmír ____ být prostě velice … ┆ ["mohla", "mohlo", … "mohl"]    ┆ 4          │
│ A tak jsem tedy ____ v tomhle … ┆ ["skončila", "skončilo", … "sk… ┆ 4          │
│ ____ jsme tenkrát, myslím, jed… ┆ ["Byla", "Bylo", … "Byl"]       ┆ 2          │
└─────────────────────────────────┴─────────────────────────────────┴────────────┘

In [13]:
df05_train = pl.from_arrow(ds05["train"].data.table)
df05_train

shape: (20, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ ["Monika  ┆ Napsali   ┆ Po dvou   ┆ … ┆ 4         ┆ 2021-02-1 ┆ 4         ┆ 56       │
│ ww.idnes. ┆ Zavřelová ┆ satirický ┆ Továrnách ┆   ┆           ┆ 8         ┆           ┆          │
│ cz/kultur ┆ "]        ┆ životopis ┆ na        ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ a/l…      ┆           ┆ Ji…       ┆ debilno   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ v…        ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Milosla ┆ Německo   ┆ Jak       ┆ … ┆ 4         ┆ 2021-04-0 ┆ 3         ┆ 29       │
│ ww.idnes. ┆ v Novák"] ┆ se        ┆ ostudné.  ┆   ┆           ┆ 1         ┆           ┆          │
│ cz/fotbal ┆           ┆ ztrapnilo ┆ Jak       ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /re…      ┆           ┆ až na     ┆ trapné.   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ kos…      ┆ Jak h…    ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Statisíce ┆ Víkendové ┆ … ┆ 4         ┆ 2021-08-1 ┆ 1         ┆ 126      │
│ ww.seznam ┆           ┆ lidí bez  ┆ devastují ┆   ┆           ┆ 9         ┆           ┆          │
│ zpravy.cz ┆           ┆ domova a  ┆ cí        ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ tr…       ┆ zemětřes… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jolana  ┆ Češi      ┆ Necelý    ┆ … ┆ 7         ┆ 2021-06-2 ┆ 1         ┆ 175      │
│ ww.seznam ┆ Humpálová ┆ letěli    ┆ rok už    ┆   ┆           ┆ 0         ┆           ┆          │
│ zpravy.cz ┆ "]        ┆ přes půl  ┆ trvá      ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ planety.  ┆ blokáda v ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆ p…        ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Ministers ┆ Ministers ┆ … ┆ 3         ┆ 2021-02-2 ┆ 2         ┆ 180      │
│ ww.irozhl ┆           ┆ tvo       ┆ tvo       ┆   ┆           ┆ 4         ┆           ┆          │
│ as.cz/zpr ┆           ┆ poslalo   ┆ školství  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ avy…      ┆           ┆ ředitelům ┆ poslalo … ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ …         ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://z ┆ ["Kateřin ┆ Hypotéka  ┆ Hypotéka  ┆ … ┆ 5         ┆ 2021-10-2 ┆ 7         ┆ 19       │
│ pravy.akt ┆ a Hovorko ┆ jako      ┆ na 40 i   ┆   ┆           ┆ 9         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ dědictví. ┆ více let  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ eko…      ┆           ┆ Banky …   ┆ se m…     ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ ["Kateřin ┆ Banky v   ┆ Po        ┆ … ┆ 4         ┆ 2021-04-2 ┆ 7         ┆ 141      │
│ pravy.akt ┆ a Hovorko ┆ Česku     ┆ několika  ┆   ┆           ┆ 9         ┆           ┆          │
│ ualne.cz/ ┆ vá"]      ┆ prochází  ┆ letech,   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ eko…      ┆           ┆ revoluc…  ┆ kdy se o  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ k…        ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Martin  ┆ Vizita:   ┆ Britský   ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2         ┆ 131      │
│ ww.seznam ┆ Čaban"]   ┆ Jak pošťo ┆ vědecký   ┆   ┆           ┆ 8         ┆           ┆          │
│ zpravy.cz ┆           ┆ uchnout k ┆ časopis   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ očk…      ┆ Nature…   ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Jiří    ┆ PŘEHLEDNĚ ┆ Stát od   ┆ … ┆ 4         ┆ 2022-06-2 ┆ 7         ┆ 10       │
│ ww.denik. ┆ Janda"]   ┆ : 500     ┆ příštího  ┆   ┆           ┆ 3         ┆           ┆          │
│ cz/ekonom ┆           ┆ korun k   ┆ roku      ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ důchodu…  ┆ přilepší… ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Posádka   ┆ Druhou    ┆ … ┆ 3         ┆ 2021-03-0 ┆ 2         ┆ 188      │
│ ww.seznam ┆           ┆ expedice  ┆ etapu ods ┆   ┆           ┆ 3         ┆           ┆          │
│ zpravy.cz ┆           ┆ Tatra     ┆ tartovala ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ kolem s…  ┆ posá…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df05_test = pl.from_arrow(ds05["test"].data.table)
df05_test

shape: (980, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ url       ┆ authors   ┆ headline  ┆ brief     ┆ … ┆ day_of_we ┆ date      ┆ __index_l ┆ __index_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ek        ┆ ---       ┆ evel_0__  ┆ level_1_ │
│ str       ┆ list[str] ┆ str       ┆ str       ┆   ┆ ---       ┆ datetime[ ┆ ---       ┆ _        │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ μs]       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ https://w ┆ []        ┆ Kaťuša    ┆ Když si   ┆ … ┆ 6         ┆ 2021-03-1 ┆ 3         ┆ 45       │
│ ww.idnes. ┆           ┆ místo     ┆ po olympi ┆   ┆           ┆ 3         ┆           ┆          │
│ cz/oh/tok ┆           ┆ hymny na  ┆ jském     ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ io-…      ┆           ┆ OH v Tok… ┆ triumfu…  ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Cena      ┆ Cena      ┆ … ┆ 2         ┆ 2021-07-2 ┆ 7         ┆ 20       │
│ ww.irozhl ┆           ┆ bitcoinu  ┆ bitcoinu  ┆   ┆           ┆ 0         ┆           ┆          │
│ as.cz/eko ┆           ┆ spadla    ┆ výrazně   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ nom…      ┆           ┆ pod 30    ┆ klesla a… ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 00…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://p ┆ ["Bohumil ┆ Obstojí v ┆ Fotbalist ┆ … ┆ 6         ┆ 2021-11-2 ┆ 3         ┆ 132      │
│ rachatick ┆ Ortman"]  ┆ sobotu    ┆ é Dynama  ┆   ┆           ┆ 7         ┆           ┆          │
│ y.denik.c ┆           ┆ Dynamo    ┆ v úvodním ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ z/f…      ┆           ┆ proti …   ┆ ko…       ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ V evropsk ┆ Zemím     ┆ … ┆ 6         ┆ 2021-02-2 ┆ 1         ┆ 127      │
│ ww.idnes. ┆           ┆ ých       ┆ Evropské  ┆   ┆           ┆ 7         ┆           ┆          │
│ cz/zpravy ┆           ┆ zemích se ┆ unie se   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /za…      ┆           ┆ hromadí…  ┆ ve skla…  ┆   ┆           ┆           ┆           ┆          │
│ https://h ┆ ["Pavla   ┆ Hradecká  ┆ Královéhr ┆ … ┆ 3         ┆ 2021-05-0 ┆ 4         ┆ 173      │
│ radecky.d ┆ Horynová" ┆ kulturní  ┆ adecké    ┆   ┆           ┆ 5         ┆           ┆          │
│ enik.cz/k ┆ ]         ┆ pátračka  ┆ kulturní  ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ult…      ┆           ┆ zpe…      ┆ organ…    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ https://w ┆ ["Martin  ┆ Ve        ┆ Jeden z   ┆ … ┆ 4         ┆ 2021-04-2 ┆ 7         ┆ 50       │
│ ww.idnes. ┆ Petříček" ┆ stopách   ┆ nejhodnot ┆   ┆           ┆ 2         ┆           ┆          │
│ cz/ekonom ┆ ]         ┆ Avastu.   ┆ nějších   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ika…      ┆           ┆ Český     ┆ start…    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ start…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ []        ┆ Památky v ┆ Hrady a   ┆ … ┆ 2         ┆ 2022-03-2 ┆ 2         ┆ 70       │
│ ww.seznam ┆           ┆ Olomoucké ┆ zámky v   ┆   ┆           ┆ 9         ┆           ┆          │
│ zpravy.cz ┆           ┆ m kraji   ┆ Olomoucké ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ /cl…      ┆           ┆ se …      ┆ m kra…    ┆   ┆           ┆           ┆           ┆          │
│ https://o ┆ ["Ivan    ┆ Přerovští ┆ Rodinu    ┆ … ┆ 3         ┆ 2021-06-3 ┆ 3         ┆ 109      │
│ lomoucky. ┆ Němeček"] ┆ hokejisté ┆ jednoho z ┆   ┆           ┆ 0         ┆           ┆          │
│ denik.cz/ ┆           ┆ pomáhali  ┆ juniorů   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ hok…      ┆           ┆ n…        ┆ přero…    ┆   ┆           ┆           ┆           ┆          │
│ https://z ┆ []        ┆ V Rusku   ┆ V Rusku   ┆ … ┆ 7         ┆ 2021-09-1 ┆ 1         ┆ 12       │
│ pravy.akt ┆           ┆ končí     ┆ pokračují ┆   ┆           ┆ 9         ┆           ┆          │
│ ualne.cz/ ┆           ┆ třídenní  ┆ třetím,   ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ zah…      ┆           ┆ parlame…  ┆ závě…     ┆   ┆           ┆           ┆           ┆          │
│ https://w ┆ ["Petr    ┆ Je to     ┆ Dvakrát   ┆ … ┆ 7         ┆ 2021-03-2 ┆ 3         ┆ 39       │
│ ww.idnes. ┆ Fojtík"]  ┆ výstraha, ┆ přebíral  ┆   ┆           ┆ 8         ┆           ┆          │
│ cz/hokej/ ┆           ┆ ohlíží se ┆ tým na    ┆   ┆           ┆ 00:00:00  ┆           ┆          │
│ ext…      ┆           ┆ kouč…     ┆ posled…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df06 = pl.from_arrow(ds06["test"].data.table)
df06

shape: (1_000, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────┬─────────────┬─────────────┐
│ url          ┆ headline     ┆ brief        ┆ keywords     ┆ category ┆ content     ┆ category_un │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---      ┆ ---         ┆ clean       │
│ str          ┆ str          ┆ str          ┆ list[str]    ┆ i64      ┆ str         ┆ ---         │
│              ┆              ┆              ┆              ┆          ┆             ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════╪═════════════╪═════════════╡
│ https://www. ┆ Soud         ┆ Pohledávky   ┆ ["Okd",      ┆ 5        ┆ V roce 2019 ┆ Ekonomika   │
│ irozhlas.cz/ ┆ potvrdil     ┆ za více než  ┆ "Citibank",  ┆          ┆ ostravský   ┆             │
│ ekonom…      ┆ platnost     ┆ deset m…     ┆ … "Pohledá…  ┆          ┆ soud roz…   ┆             │
│              ┆ pohledá…     ┆              ┆              ┆          ┆             ┆             │
│ https://www. ┆ Lego chce    ┆ Lego bude    ┆ []           ┆ 5        ┆ Na zavádění ┆ Ekonomika   │
│ novinky.cz/e ┆ dát vale     ┆ balit        ┆              ┆          ┆ nového typu ┆             │
│ konomi…      ┆ plastovým o… ┆ stavebnice   ┆              ┆          ┆ balení…     ┆             │
│              ┆              ┆ do …         ┆              ┆          ┆             ┆             │
│ https://www. ┆ Hypoteční    ┆ Objem        ┆ ["Česká      ┆ 5        ┆ Nad touto   ┆ Ekonomika   │
│ idnes.cz/eko ┆ mejdan       ┆ poskytnutých ┆ spořitelna", ┆          ┆ hranicí     ┆             │
│ nomika…      ┆ končí, úvěry ┆ hypoték za … ┆ "Čnb - če…   ┆          ┆ byla        ┆             │
│              ┆ …            ┆              ┆              ┆          ┆ průměrn…    ┆             │
│ https://www. ┆ K            ┆ Možností,    ┆ []           ┆ 5        ┆ Milostivé   ┆ Ekonomika   │
│ novinky.cz/e ┆ Milostivému  ┆ jak se v     ┆              ┆          ┆ léto je     ┆             │
│ konomi…      ┆ létu se      ┆ rámci tzv. … ┆              ┆          ┆ novelou     ┆             │
│              ┆ přidaly …    ┆              ┆              ┆          ┆ exek…       ┆             │
│ https://www. ┆ V evropských ┆ Zemím        ┆ ["Francie",  ┆ 1        ┆ Například   ┆ Zahraničí   │
│ idnes.cz/zpr ┆ zemích se    ┆ Evropské     ┆ "Itálie", …  ┆          ┆ Francie do  ┆             │
│ avy/za…      ┆ hromadí…     ┆ unie se ve   ┆ "Paříž…      ┆          ┆ pátku zuž…  ┆             │
│              ┆              ┆ skla…        ┆              ┆          ┆             ┆             │
│ …            ┆ …            ┆ …            ┆ …            ┆ …        ┆ …           ┆ …           │
│ https://www. ┆ Fotbalový    ┆ Z role       ┆ ["Liberecký  ┆ 3        ┆ Sadílek je  ┆ Fotbal      │
│ idnes.cz/fot ┆ pracant?     ┆ pracanta ve  ┆ kraj",       ┆          ┆ pod         ┆             │
│ bal/pr…      ┆ Sadílek se … ┆ středu pole… ┆ "Michal sad… ┆          ┆ Ještědem od ┆             │
│              ┆              ┆              ┆              ┆          ┆ loň…        ┆             │
│ https://maga ┆ Zesnulý      ┆ Skoro jako   ┆ ["Hudba",    ┆ 4        ┆ Jóhannssono ┆ Film        │
│ zin.aktualne ┆ Islanďan     ┆ by po obloze ┆ "Jóhann jóha ┆          ┆ vo experime ┆             │
│ .cz/ku…      ┆ Jóhannsson   ┆ připlo…      ┆ nnsson",…    ┆          ┆ ntální s…   ┆             │
│              ┆ sk…          ┆              ┆              ┆          ┆             ┆             │
│ https://zpra ┆ HN: Mall     ┆ Společnost   ┆ ["Burza",    ┆ 5        ┆ Uvedení     ┆ Ekonomika   │
│ vy.aktualne. ┆ Group        ┆ Mall Group,  ┆ "Hospodářské ┆          ┆ akcionáři   ┆             │
│ cz/eko…      ┆ zvažuje      ┆ která p…     ┆ noviny"…     ┆          ┆ uvažují o   ┆             │
│              ┆ vstup n…     ┆              ┆              ┆          ┆ pr…         ┆             │
│ https://www. ┆ Sbírky       ┆ Americký     ┆ ["Ethereum", ┆ 5        ┆ Mattel      ┆ Ekonomika   │
│ idnes.cz/eko ┆ autíček už   ┆ výrobce      ┆ "Nft", …     ┆          ┆ vydraží svá ┆             │
│ nomika…      ┆ nebudou co   ┆ hraček       ┆ "Hot whe…    ┆          ┆ auta Hot    ┆             │
│              ┆ b…           ┆ využij…      ┆              ┆          ┆ Wh…         ┆             │
│ https://www. ┆ ‚Máte        ┆ Vítězkou     ┆ ["Praha",    ┆ 4        ┆ Mladá       ┆ Kultura     │
│ irozhlas.cz/ ┆ fyzický      ┆ ceny hudební ┆ "Česko", …   ┆          ┆ nezávislá   ┆             │
│ kultur…      ┆ pocit, že    ┆ kritiky …    ┆ "Hudba"]     ┆          ┆ písničkářka ┆             │
│              ┆ zpívá …      ┆              ┆              ┆          ┆ z …         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────┴─────────────┴─────────────┘